//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:14 AM IST 
//


package com.hp.cdsplus.bindings.output.schema.productmastercache;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hp.com/cdsplus}source"/>
 *         &lt;element ref="{}marketing_category"/>
 *         &lt;element ref="{}marketing_subcategory"/>
 *         &lt;element ref="{}old_one"/>
 *         &lt;element ref="{}product_big_series"/>
 *         &lt;element ref="{}product_name"/>
 *         &lt;element ref="{}product_number"/>
 *         &lt;element ref="{}product_series"/>
 *         &lt;element ref="{}product_type"/>
 *         &lt;element ref="{}support_category"/>
 *         &lt;element ref="{}support_subcategory"/>
 *         &lt;element ref="{}support_name_oids"/>
 *         &lt;element ref="{}product_lines"/>
 *         &lt;element ref="{}product_numbers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "marketingCategory",
    "marketingSubcategory",
    "oldOne",
    "productBigSeries",
    "productName",
    "productNumber",
    "productSeries",
    "productType",
    "supportCategory",
    "supportSubcategory",
    "supportNameOids",
    "productLines",
    "productNumbers"
})
@XmlRootElement(name = "view")
public class View {

    @XmlElement(namespace = "http://www.hp.com/cdsplus", required = true)
    protected Source source;
    @XmlElement(name = "marketing_category", required = true)
    protected MarketingCategory marketingCategory;
    @XmlElement(name = "marketing_subcategory", required = true)
    protected MarketingSubcategory marketingSubcategory;
    @XmlElement(name = "old_one", required = true)
    protected OldOne oldOne;
    @XmlElement(name = "product_big_series", required = true)
    protected ProductBigSeries productBigSeries;
    @XmlElement(name = "product_name", required = true)
    protected ProductName productName;
    @XmlElement(name = "product_number", required = true)
    protected ProductNumber productNumber;
    @XmlElement(name = "product_series", required = true)
    protected ProductSeries productSeries;
    @XmlElement(name = "product_type", required = true)
    protected ProductType productType;
    @XmlElement(name = "support_category", required = true)
    protected SupportCategory supportCategory;
    @XmlElement(name = "support_subcategory", required = true)
    protected SupportSubcategory supportSubcategory;
    @XmlElement(name = "support_name_oids", required = true)
    protected SupportNameOids supportNameOids;
    @XmlElement(name = "product_lines", required = true)
    protected ProductLines productLines;
    @XmlElement(name = "product_numbers", required = true)
    protected ProductNumbers productNumbers;
    @XmlAttribute(required = true)
    protected BigInteger oid;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String base;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the marketingCategory property.
     * 
     * @return
     *     possible object is
     *     {@link MarketingCategory }
     *     
     */
    public MarketingCategory getMarketingCategory() {
        return marketingCategory;
    }

    /**
     * Sets the value of the marketingCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketingCategory }
     *     
     */
    public void setMarketingCategory(MarketingCategory value) {
        this.marketingCategory = value;
    }

    /**
     * Gets the value of the marketingSubcategory property.
     * 
     * @return
     *     possible object is
     *     {@link MarketingSubcategory }
     *     
     */
    public MarketingSubcategory getMarketingSubcategory() {
        return marketingSubcategory;
    }

    /**
     * Sets the value of the marketingSubcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketingSubcategory }
     *     
     */
    public void setMarketingSubcategory(MarketingSubcategory value) {
        this.marketingSubcategory = value;
    }

    /**
     * Gets the value of the oldOne property.
     * 
     * @return
     *     possible object is
     *     {@link OldOne }
     *     
     */
    public OldOne getOldOne() {
        return oldOne;
    }

    /**
     * Sets the value of the oldOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link OldOne }
     *     
     */
    public void setOldOne(OldOne value) {
        this.oldOne = value;
    }

    /**
     * Gets the value of the productBigSeries property.
     * 
     * @return
     *     possible object is
     *     {@link ProductBigSeries }
     *     
     */
    public ProductBigSeries getProductBigSeries() {
        return productBigSeries;
    }

    /**
     * Sets the value of the productBigSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductBigSeries }
     *     
     */
    public void setProductBigSeries(ProductBigSeries value) {
        this.productBigSeries = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link ProductName }
     *     
     */
    public ProductName getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductName }
     *     
     */
    public void setProductName(ProductName value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ProductNumber }
     *     
     */
    public ProductNumber getProductNumber() {
        return productNumber;
    }

    /**
     * Sets the value of the productNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductNumber }
     *     
     */
    public void setProductNumber(ProductNumber value) {
        this.productNumber = value;
    }

    /**
     * Gets the value of the productSeries property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSeries }
     *     
     */
    public ProductSeries getProductSeries() {
        return productSeries;
    }

    /**
     * Sets the value of the productSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSeries }
     *     
     */
    public void setProductSeries(ProductSeries value) {
        this.productSeries = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProductType(ProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the supportCategory property.
     * 
     * @return
     *     possible object is
     *     {@link SupportCategory }
     *     
     */
    public SupportCategory getSupportCategory() {
        return supportCategory;
    }

    /**
     * Sets the value of the supportCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportCategory }
     *     
     */
    public void setSupportCategory(SupportCategory value) {
        this.supportCategory = value;
    }

    /**
     * Gets the value of the supportSubcategory property.
     * 
     * @return
     *     possible object is
     *     {@link SupportSubcategory }
     *     
     */
    public SupportSubcategory getSupportSubcategory() {
        return supportSubcategory;
    }

    /**
     * Sets the value of the supportSubcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportSubcategory }
     *     
     */
    public void setSupportSubcategory(SupportSubcategory value) {
        this.supportSubcategory = value;
    }

    /**
     * Gets the value of the supportNameOids property.
     * 
     * @return
     *     possible object is
     *     {@link SupportNameOids }
     *     
     */
    public SupportNameOids getSupportNameOids() {
        return supportNameOids;
    }

    /**
     * Sets the value of the supportNameOids property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportNameOids }
     *     
     */
    public void setSupportNameOids(SupportNameOids value) {
        this.supportNameOids = value;
    }

    /**
     * Gets the value of the productLines property.
     * 
     * @return
     *     possible object is
     *     {@link ProductLines }
     *     
     */
    public ProductLines getProductLines() {
        return productLines;
    }

    /**
     * Sets the value of the productLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductLines }
     *     
     */
    public void setProductLines(ProductLines value) {
        this.productLines = value;
    }

    /**
     * Gets the value of the productNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ProductNumbers }
     *     
     */
    public ProductNumbers getProductNumbers() {
        return productNumbers;
    }

    /**
     * Sets the value of the productNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductNumbers }
     *     
     */
    public void setProductNumbers(ProductNumbers value) {
        this.productNumbers = value;
    }

    /**
     * Gets the value of the oid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOid() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOid(BigInteger value) {
        this.oid = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
