//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:14 AM IST 
//


package com.hp.cdsplus.bindings.output.schema.librarycontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}callout"/>
 *         &lt;element ref="{}image"/>
 *         &lt;element ref="{}label"/>
 *       &lt;/choice>
 *       &lt;attribute name="component.title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reuse" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "graphic")
public class Graphic {

    @XmlElementRefs({
        @XmlElementRef(name = "image", type = Image.class),
        @XmlElementRef(name = "label", type = JAXBElement.class),
        @XmlElementRef(name = "callout", type = Callout.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "component.title", required = true)
    protected String componentTitle;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reuse;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Callout }
     * {@link String }
     * {@link Image }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the componentTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentTitle() {
        return componentTitle;
    }

    /**
     * Sets the value of the componentTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentTitle(String value) {
        this.componentTitle = value;
    }

    /**
     * Gets the value of the reuse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReuse() {
        return reuse;
    }

    /**
     * Sets the value of the reuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReuse(String value) {
        this.reuse = value;
    }

}
