//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:10 AM IST 
//


package com.hp.concentra.bindings.output.schema.contentfeedback;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}action" minOccurs="0"/>
 *         &lt;element ref="{}company_info"/>
 *         &lt;element ref="{}r_object_id"/>
 *         &lt;element ref="{}priority"/>
 *         &lt;element ref="{}products"/>
 *         &lt;element ref="{}product_types" minOccurs="0"/>
 *         &lt;element ref="{}product_big_series" minOccurs="0"/>
 *         &lt;element ref="{}support_name_oids" minOccurs="0"/>
 *         &lt;element ref="{}product_support_categories" minOccurs="0"/>
 *         &lt;element ref="{}product_support_subcategories" minOccurs="0"/>
 *         &lt;element ref="{}product_series" minOccurs="0"/>
 *         &lt;element ref="{}product_names" minOccurs="0"/>
 *         &lt;element ref="{}product_number_names" minOccurs="0"/>
 *         &lt;element ref="{}product_numbers" minOccurs="0"/>
 *         &lt;element ref="{}product_lines" minOccurs="0"/>
 *         &lt;element ref="{}product_marketing_categories" minOccurs="0"/>
 *         &lt;element ref="{}product_marketing_subcategories" minOccurs="0"/>
 *         &lt;element ref="{}document_type"/>
 *         &lt;element ref="{}version_label"/>
 *         &lt;element ref="{}feedback_product_lines"/>
 *         &lt;element ref="{}content_type"/>
 *         &lt;element ref="{}regions"/>
 *         &lt;element ref="{}property_update_date"/>
 *         &lt;element ref="{}language_label"/>
 *         &lt;element ref="{}information_source"/>
 *         &lt;element ref="{}full_title"/>
 *         &lt;element ref="{}action_requested"/>
 *         &lt;element ref="{}action_taken"/>
 *         &lt;element ref="{}confidential_comment"/>
 *         &lt;element ref="{}feedback_content_name"/>
 *         &lt;element ref="{}original_system"/>
 *         &lt;element ref="{}feedback_priority"/>
 *         &lt;element ref="{}document_class"/>
 *         &lt;element ref="{}file_bytes"/>
 *         &lt;element ref="{}language_code"/>
 *         &lt;element ref="{}miscellaneous_comment"/>
 *         &lt;element ref="{}object_name"/>
 *         &lt;element ref="{}original_docid"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "action",
    "companyInfo",
    "rObjectId",
    "priority",
    "products",
    "productTypes",
    "productBigSeries",
    "supportNameOids",
    "productSupportCategories",
    "productSupportSubcategories",
    "productSeries",
    "productNames",
    "productNumberNames",
    "productNumbers",
    "productLines",
    "productMarketingCategories",
    "productMarketingSubcategories",
    "documentType",
    "versionLabel",
    "feedbackProductLines",
    "contentType",
    "regions",
    "propertyUpdateDate",
    "languageLabel",
    "informationSource",
    "fullTitle",
    "actionRequested",
    "actionTaken",
    "confidentialComment",
    "feedbackContentName",
    "originalSystem",
    "feedbackPriority",
    "documentClass",
    "fileBytes",
    "languageCode",
    "miscellaneousComment",
    "objectName",
    "originalDocid"
})
@XmlRootElement(name = "document")
public class Document {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String action;
    @XmlElement(name = "company_info", required = true)
    protected String companyInfo;
    @XmlElement(name = "r_object_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rObjectId;
    @XmlElement(required = true)
    protected BigInteger priority;
    @XmlElement(required = true)
    protected Products products;
    @XmlElement(name = "product_types")
    protected ProductTypes productTypes;
    @XmlElement(name = "product_big_series")
    protected ProductBigSeries productBigSeries;
    @XmlElement(name = "support_name_oids")
    protected SupportNameOids supportNameOids;
    @XmlElement(name = "product_support_categories")
    protected ProductSupportCategories productSupportCategories;
    @XmlElement(name = "product_support_subcategories")
    protected ProductSupportSubcategories productSupportSubcategories;
    @XmlElement(name = "product_series")
    protected ProductSeries productSeries;
    @XmlElement(name = "product_names")
    protected ProductNames productNames;
    @XmlElement(name = "product_number_names")
    protected ProductNumberNames productNumberNames;
    @XmlElement(name = "product_numbers")
    protected ProductNumbers productNumbers;
    @XmlElement(name = "product_lines")
    protected ProductLines productLines;
    @XmlElement(name = "product_marketing_categories")
    protected ProductMarketingCategories productMarketingCategories;
    @XmlElement(name = "product_marketing_subcategories")
    protected ProductMarketingSubcategories productMarketingSubcategories;
    @XmlElement(name = "document_type", required = true)
    protected String documentType;
    @XmlElement(name = "version_label", required = true)
    protected String versionLabel;
    @XmlElement(name = "feedback_product_lines", required = true)
    protected FeedbackProductLines feedbackProductLines;
    @XmlElement(name = "content_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String contentType;
    @XmlElement(required = true)
    protected Regions regions;
    @XmlElement(name = "property_update_date", required = true, nillable = true)
    protected XMLGregorianCalendar propertyUpdateDate;
    @XmlElement(name = "language_label", required = true)
    protected String languageLabel;
    @XmlElement(name = "information_source", required = true)
    protected String informationSource;
    @XmlElement(name = "full_title", required = true)
    protected FullTitle fullTitle;
    @XmlElement(name = "action_requested", required = true)
    protected String actionRequested;
    @XmlElement(name = "action_taken", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String actionTaken;
    @XmlElement(name = "confidential_comment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String confidentialComment;
    @XmlElement(name = "feedback_content_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String feedbackContentName;
    @XmlElement(name = "original_system", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalSystem;
    @XmlElement(name = "feedback_priority", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String feedbackPriority;
    @XmlElement(name = "document_class", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String documentClass;
    @XmlElement(name = "file_bytes", required = true)
    protected BigInteger fileBytes;
    @XmlElement(name = "language_code", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String languageCode;
    @XmlElement(name = "miscellaneous_comment", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String miscellaneousComment;
    @XmlElement(name = "object_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String objectName;
    @XmlElement(name = "original_docid", required = true)
    protected String originalDocid;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String base;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the companyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyInfo() {
        return companyInfo;
    }

    /**
     * Sets the value of the companyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyInfo(String value) {
        this.companyInfo = value;
    }

    /**
     * Gets the value of the rObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRObjectId() {
        return rObjectId;
    }

    /**
     * Sets the value of the rObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRObjectId(String value) {
        this.rObjectId = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link Products }
     *     
     */
    public Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link Products }
     *     
     */
    public void setProducts(Products value) {
        this.products = value;
    }

    /**
     * Gets the value of the productTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ProductTypes }
     *     
     */
    public ProductTypes getProductTypes() {
        return productTypes;
    }

    /**
     * Sets the value of the productTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductTypes }
     *     
     */
    public void setProductTypes(ProductTypes value) {
        this.productTypes = value;
    }

    /**
     * Gets the value of the productBigSeries property.
     * 
     * @return
     *     possible object is
     *     {@link ProductBigSeries }
     *     
     */
    public ProductBigSeries getProductBigSeries() {
        return productBigSeries;
    }

    /**
     * Sets the value of the productBigSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductBigSeries }
     *     
     */
    public void setProductBigSeries(ProductBigSeries value) {
        this.productBigSeries = value;
    }

    /**
     * Gets the value of the supportNameOids property.
     * 
     * @return
     *     possible object is
     *     {@link SupportNameOids }
     *     
     */
    public SupportNameOids getSupportNameOids() {
        return supportNameOids;
    }

    /**
     * Sets the value of the supportNameOids property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportNameOids }
     *     
     */
    public void setSupportNameOids(SupportNameOids value) {
        this.supportNameOids = value;
    }

    /**
     * Gets the value of the productSupportCategories property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSupportCategories }
     *     
     */
    public ProductSupportCategories getProductSupportCategories() {
        return productSupportCategories;
    }

    /**
     * Sets the value of the productSupportCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSupportCategories }
     *     
     */
    public void setProductSupportCategories(ProductSupportCategories value) {
        this.productSupportCategories = value;
    }

    /**
     * Gets the value of the productSupportSubcategories property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSupportSubcategories }
     *     
     */
    public ProductSupportSubcategories getProductSupportSubcategories() {
        return productSupportSubcategories;
    }

    /**
     * Sets the value of the productSupportSubcategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSupportSubcategories }
     *     
     */
    public void setProductSupportSubcategories(ProductSupportSubcategories value) {
        this.productSupportSubcategories = value;
    }

    /**
     * Gets the value of the productSeries property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSeries }
     *     
     */
    public ProductSeries getProductSeries() {
        return productSeries;
    }

    /**
     * Sets the value of the productSeries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSeries }
     *     
     */
    public void setProductSeries(ProductSeries value) {
        this.productSeries = value;
    }

    /**
     * Gets the value of the productNames property.
     * 
     * @return
     *     possible object is
     *     {@link ProductNames }
     *     
     */
    public ProductNames getProductNames() {
        return productNames;
    }

    /**
     * Sets the value of the productNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductNames }
     *     
     */
    public void setProductNames(ProductNames value) {
        this.productNames = value;
    }

    /**
     * Gets the value of the productNumberNames property.
     * 
     * @return
     *     possible object is
     *     {@link ProductNumberNames }
     *     
     */
    public ProductNumberNames getProductNumberNames() {
        return productNumberNames;
    }

    /**
     * Sets the value of the productNumberNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductNumberNames }
     *     
     */
    public void setProductNumberNames(ProductNumberNames value) {
        this.productNumberNames = value;
    }

    /**
     * Gets the value of the productNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ProductNumbers }
     *     
     */
    public ProductNumbers getProductNumbers() {
        return productNumbers;
    }

    /**
     * Sets the value of the productNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductNumbers }
     *     
     */
    public void setProductNumbers(ProductNumbers value) {
        this.productNumbers = value;
    }

    /**
     * Gets the value of the productLines property.
     * 
     * @return
     *     possible object is
     *     {@link ProductLines }
     *     
     */
    public ProductLines getProductLines() {
        return productLines;
    }

    /**
     * Sets the value of the productLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductLines }
     *     
     */
    public void setProductLines(ProductLines value) {
        this.productLines = value;
    }

    /**
     * Gets the value of the productMarketingCategories property.
     * 
     * @return
     *     possible object is
     *     {@link ProductMarketingCategories }
     *     
     */
    public ProductMarketingCategories getProductMarketingCategories() {
        return productMarketingCategories;
    }

    /**
     * Sets the value of the productMarketingCategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductMarketingCategories }
     *     
     */
    public void setProductMarketingCategories(ProductMarketingCategories value) {
        this.productMarketingCategories = value;
    }

    /**
     * Gets the value of the productMarketingSubcategories property.
     * 
     * @return
     *     possible object is
     *     {@link ProductMarketingSubcategories }
     *     
     */
    public ProductMarketingSubcategories getProductMarketingSubcategories() {
        return productMarketingSubcategories;
    }

    /**
     * Sets the value of the productMarketingSubcategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductMarketingSubcategories }
     *     
     */
    public void setProductMarketingSubcategories(ProductMarketingSubcategories value) {
        this.productMarketingSubcategories = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the versionLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionLabel() {
        return versionLabel;
    }

    /**
     * Sets the value of the versionLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionLabel(String value) {
        this.versionLabel = value;
    }

    /**
     * Gets the value of the feedbackProductLines property.
     * 
     * @return
     *     possible object is
     *     {@link FeedbackProductLines }
     *     
     */
    public FeedbackProductLines getFeedbackProductLines() {
        return feedbackProductLines;
    }

    /**
     * Sets the value of the feedbackProductLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedbackProductLines }
     *     
     */
    public void setFeedbackProductLines(FeedbackProductLines value) {
        this.feedbackProductLines = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link Regions }
     *     
     */
    public Regions getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regions }
     *     
     */
    public void setRegions(Regions value) {
        this.regions = value;
    }

    /**
     * Gets the value of the propertyUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPropertyUpdateDate() {
        return propertyUpdateDate;
    }

    /**
     * Sets the value of the propertyUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPropertyUpdateDate(XMLGregorianCalendar value) {
        this.propertyUpdateDate = value;
    }

    /**
     * Gets the value of the languageLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageLabel() {
        return languageLabel;
    }

    /**
     * Sets the value of the languageLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageLabel(String value) {
        this.languageLabel = value;
    }

    /**
     * Gets the value of the informationSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationSource() {
        return informationSource;
    }

    /**
     * Sets the value of the informationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationSource(String value) {
        this.informationSource = value;
    }

    /**
     * Gets the value of the fullTitle property.
     * 
     * @return
     *     possible object is
     *     {@link FullTitle }
     *     
     */
    public FullTitle getFullTitle() {
        return fullTitle;
    }

    /**
     * Sets the value of the fullTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullTitle }
     *     
     */
    public void setFullTitle(FullTitle value) {
        this.fullTitle = value;
    }

    /**
     * Gets the value of the actionRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionRequested() {
        return actionRequested;
    }

    /**
     * Sets the value of the actionRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionRequested(String value) {
        this.actionRequested = value;
    }

    /**
     * Gets the value of the actionTaken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionTaken() {
        return actionTaken;
    }

    /**
     * Sets the value of the actionTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionTaken(String value) {
        this.actionTaken = value;
    }

    /**
     * Gets the value of the confidentialComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialComment() {
        return confidentialComment;
    }

    /**
     * Sets the value of the confidentialComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialComment(String value) {
        this.confidentialComment = value;
    }

    /**
     * Gets the value of the feedbackContentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeedbackContentName() {
        return feedbackContentName;
    }

    /**
     * Sets the value of the feedbackContentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeedbackContentName(String value) {
        this.feedbackContentName = value;
    }

    /**
     * Gets the value of the originalSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalSystem() {
        return originalSystem;
    }

    /**
     * Sets the value of the originalSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalSystem(String value) {
        this.originalSystem = value;
    }

    /**
     * Gets the value of the feedbackPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeedbackPriority() {
        return feedbackPriority;
    }

    /**
     * Sets the value of the feedbackPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeedbackPriority(String value) {
        this.feedbackPriority = value;
    }

    /**
     * Gets the value of the documentClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentClass() {
        return documentClass;
    }

    /**
     * Sets the value of the documentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentClass(String value) {
        this.documentClass = value;
    }

    /**
     * Gets the value of the fileBytes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFileBytes() {
        return fileBytes;
    }

    /**
     * Sets the value of the fileBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFileBytes(BigInteger value) {
        this.fileBytes = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the miscellaneousComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscellaneousComment() {
        return miscellaneousComment;
    }

    /**
     * Sets the value of the miscellaneousComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscellaneousComment(String value) {
        this.miscellaneousComment = value;
    }

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the originalDocid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDocid() {
        return originalDocid;
    }

    /**
     * Sets the value of the originalDocid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDocid(String value) {
        this.originalDocid = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
