//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:10 AM IST 
//


package com.hp.concentra.bindings.output.schema.contentfeedback;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hp.concentra.bindings.output.schema.contentfeedback package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FeedbackContentName_QNAME = new QName("", "feedback_content_name");
    private final static QName _VersionLabel_QNAME = new QName("", "version_label");
    private final static QName _ActionRequested_QNAME = new QName("", "action_requested");
    private final static QName _MiscellaneousComment_QNAME = new QName("", "miscellaneous_comment");
    private final static QName _RObjectId_QNAME = new QName("", "r_object_id");
    private final static QName _CompanyInfo_QNAME = new QName("", "company_info");
    private final static QName _ActionTaken_QNAME = new QName("", "action_taken");
    private final static QName _FeedbackPriority_QNAME = new QName("", "feedback_priority");
    private final static QName _OriginalDocid_QNAME = new QName("", "original_docid");
    private final static QName _FileBytes_QNAME = new QName("", "file_bytes");
    private final static QName _Priority_QNAME = new QName("", "priority");
    private final static QName _InformationSource_QNAME = new QName("", "information_source");
    private final static QName _OriginalSystem_QNAME = new QName("", "original_system");
    private final static QName _FeedbackProductLine_QNAME = new QName("", "feedback_product_line");
    private final static QName _LanguageCode_QNAME = new QName("", "language_code");
    private final static QName _DocumentClass_QNAME = new QName("", "document_class");
    private final static QName _ContentType_QNAME = new QName("", "content_type");
    private final static QName _LanguageLabel_QNAME = new QName("", "language_label");
    private final static QName _ConfidentialComment_QNAME = new QName("", "confidential_comment");
    private final static QName _ObjectName_QNAME = new QName("", "object_name");
    private final static QName _Action_QNAME = new QName("", "action");
    private final static QName _Region_QNAME = new QName("", "region");
    private final static QName _DocumentType_QNAME = new QName("", "document_type");
    private final static QName _PropertyUpdateDate_QNAME = new QName("", "property_update_date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hp.concentra.bindings.output.schema.contentfeedback
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductName }
     * 
     */
    public ProductName createProductName() {
        return new ProductName();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link ProductMarketingSubcategories }
     * 
     */
    public ProductMarketingSubcategories createProductMarketingSubcategories() {
        return new ProductMarketingSubcategories();
    }

    /**
     * Create an instance of {@link FullTitle }
     * 
     */
    public FullTitle createFullTitle() {
        return new FullTitle();
    }

    /**
     * Create an instance of {@link SupportNameOids }
     * 
     */
    public SupportNameOids createSupportNameOids() {
        return new SupportNameOids();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ProductSeries }
     * 
     */
    public ProductSeries createProductSeries() {
        return new ProductSeries();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link SupportSubcategory }
     * 
     */
    public SupportSubcategory createSupportSubcategory() {
        return new SupportSubcategory();
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link ProductNumbers }
     * 
     */
    public ProductNumbers createProductNumbers() {
        return new ProductNumbers();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link Projectref }
     * 
     */
    public Projectref createProjectref() {
        return new Projectref();
    }

    /**
     * Create an instance of {@link ProductBigSeries }
     * 
     */
    public ProductBigSeries createProductBigSeries() {
        return new ProductBigSeries();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link ProductSupportSubcategories }
     * 
     */
    public ProductSupportSubcategories createProductSupportSubcategories() {
        return new ProductSupportSubcategories();
    }

    /**
     * Create an instance of {@link ProductNumberNames }
     * 
     */
    public ProductNumberNames createProductNumberNames() {
        return new ProductNumberNames();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link FeedbackProductLines }
     * 
     */
    public FeedbackProductLines createFeedbackProductLines() {
        return new FeedbackProductLines();
    }

    /**
     * Create an instance of {@link Regions }
     * 
     */
    public Regions createRegions() {
        return new Regions();
    }

    /**
     * Create an instance of {@link ProductSupportCategories }
     * 
     */
    public ProductSupportCategories createProductSupportCategories() {
        return new ProductSupportCategories();
    }

    /**
     * Create an instance of {@link ProductNames }
     * 
     */
    public ProductNames createProductNames() {
        return new ProductNames();
    }

    /**
     * Create an instance of {@link ProductTypes }
     * 
     */
    public ProductTypes createProductTypes() {
        return new ProductTypes();
    }

    /**
     * Create an instance of {@link ProductLines }
     * 
     */
    public ProductLines createProductLines() {
        return new ProductLines();
    }

    /**
     * Create an instance of {@link ProductMarketingCategories }
     * 
     */
    public ProductMarketingCategories createProductMarketingCategories() {
        return new ProductMarketingCategories();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "feedback_content_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFeedbackContentName(String value) {
        return new JAXBElement<String>(_FeedbackContentName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version_label")
    public JAXBElement<String> createVersionLabel(String value) {
        return new JAXBElement<String>(_VersionLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action_requested")
    public JAXBElement<String> createActionRequested(String value) {
        return new JAXBElement<String>(_ActionRequested_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "miscellaneous_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMiscellaneousComment(String value) {
        return new JAXBElement<String>(_MiscellaneousComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "r_object_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRObjectId(String value) {
        return new JAXBElement<String>(_RObjectId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company_info")
    public JAXBElement<String> createCompanyInfo(String value) {
        return new JAXBElement<String>(_CompanyInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action_taken")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createActionTaken(String value) {
        return new JAXBElement<String>(_ActionTaken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "feedback_priority")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFeedbackPriority(String value) {
        return new JAXBElement<String>(_FeedbackPriority_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original_docid")
    public JAXBElement<String> createOriginalDocid(String value) {
        return new JAXBElement<String>(_OriginalDocid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "file_bytes")
    public JAXBElement<BigInteger> createFileBytes(BigInteger value) {
        return new JAXBElement<BigInteger>(_FileBytes_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority")
    public JAXBElement<BigInteger> createPriority(BigInteger value) {
        return new JAXBElement<BigInteger>(_Priority_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "information_source")
    public JAXBElement<String> createInformationSource(String value) {
        return new JAXBElement<String>(_InformationSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original_system")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalSystem(String value) {
        return new JAXBElement<String>(_OriginalSystem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "feedback_product_line")
    public JAXBElement<String> createFeedbackProductLine(String value) {
        return new JAXBElement<String>(_FeedbackProductLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language_code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguageCode(String value) {
        return new JAXBElement<String>(_LanguageCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "document_class")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDocumentClass(String value) {
        return new JAXBElement<String>(_DocumentClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createContentType(String value) {
        return new JAXBElement<String>(_ContentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language_label")
    public JAXBElement<String> createLanguageLabel(String value) {
        return new JAXBElement<String>(_LanguageLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "confidential_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createConfidentialComment(String value) {
        return new JAXBElement<String>(_ConfidentialComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "object_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createObjectName(String value) {
        return new JAXBElement<String>(_ObjectName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "document_type")
    public JAXBElement<String> createDocumentType(String value) {
        return new JAXBElement<String>(_DocumentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property_update_date")
    public JAXBElement<XMLGregorianCalendar> createPropertyUpdateDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PropertyUpdateDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
