//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:15 AM IST 
//


package com.hp.msc.bindings.input.schema.richmedia;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hp.msc.bindings.input.schema.richmedia package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hp.msc.bindings.input.schema.richmedia
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssetRendition.CountryCodes }
     * 
     */
    public AssetRendition.CountryCodes createAssetRenditionCountryCodes() {
        return new AssetRendition.CountryCodes();
    }

    /**
     * Create an instance of {@link AssetRendition.LanguageCodes }
     * 
     */
    public AssetRendition.LanguageCodes createAssetRenditionLanguageCodes() {
        return new AssetRendition.LanguageCodes();
    }

    /**
     * Create an instance of {@link AssetRendition.RelatedLinkLabels }
     * 
     */
    public AssetRendition.RelatedLinkLabels createAssetRenditionRelatedLinkLabels() {
        return new AssetRendition.RelatedLinkLabels();
    }

    /**
     * Create an instance of {@link AssetRendition.ProductLevels }
     * 
     */
    public AssetRendition.ProductLevels createAssetRenditionProductLevels() {
        return new AssetRendition.ProductLevels();
    }

    /**
     * Create an instance of {@link AssetRendition.UsageRights }
     * 
     */
    public AssetRendition.UsageRights createAssetRenditionUsageRights() {
        return new AssetRendition.UsageRights();
    }

    /**
     * Create an instance of {@link AssetRendition.Products }
     * 
     */
    public AssetRendition.Products createAssetRenditionProducts() {
        return new AssetRendition.Products();
    }

    /**
     * Create an instance of {@link AssetRendition.BcRelatedPlaylists }
     * 
     */
    public AssetRendition.BcRelatedPlaylists createAssetRenditionBcRelatedPlaylists() {
        return new AssetRendition.BcRelatedPlaylists();
    }

    /**
     * Create an instance of {@link AssetRendition }
     * 
     */
    public AssetRendition createAssetRendition() {
        return new AssetRendition();
    }

    /**
     * Create an instance of {@link AssetRendition.SearchKeywords }
     * 
     */
    public AssetRendition.SearchKeywords createAssetRenditionSearchKeywords() {
        return new AssetRendition.SearchKeywords();
    }

    /**
     * Create an instance of {@link AssetRendition.BusinessUnits }
     * 
     */
    public AssetRendition.BusinessUnits createAssetRenditionBusinessUnits() {
        return new AssetRendition.BusinessUnits();
    }

    /**
     * Create an instance of {@link AssetRendition.CustomerSegments }
     * 
     */
    public AssetRendition.CustomerSegments createAssetRenditionCustomerSegments() {
        return new AssetRendition.CustomerSegments();
    }

    /**
     * Create an instance of {@link AssetRendition.RelatedLinkUrls }
     * 
     */
    public AssetRendition.RelatedLinkUrls createAssetRenditionRelatedLinkUrls() {
        return new AssetRendition.RelatedLinkUrls();
    }

}
