//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:04 AM IST 
//


package com.hp.concentra.bindings.input.schema.support;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}company_info"/>
 *         &lt;element ref="{}r_object_id"/>
 *         &lt;element ref="{}priority"/>
 *         &lt;element ref="{}products"/>
 *         &lt;element ref="{}document_type"/>
 *         &lt;element ref="{}version_label"/>
 *         &lt;element ref="{}taxonomy_categorizations"/>
 *         &lt;element ref="{}property_update_date"/>
 *         &lt;element ref="{}content_update_date"/>
 *         &lt;element ref="{}active_flag"/>
 *         &lt;element ref="{}content_update_user"/>
 *         &lt;element ref="{}future_disclosure_date"/>
 *         &lt;element ref="{}future_disclosure_level"/>
 *         &lt;element ref="{}is_translation_flag"/>
 *         &lt;element ref="{}lifecycle_state_update_date"/>
 *         &lt;element ref="{}lifecycle_state_update_user"/>
 *         &lt;element ref="{}property_update_user"/>
 *         &lt;element ref="{}cmg_name"/>
 *         &lt;element ref="{}col_master_id"/>
 *         &lt;element ref="{}collection_ref_update_date"/>
 *         &lt;element ref="{}collection_update_date"/>
 *         &lt;element ref="{}collection_update_user"/>
 *         &lt;element ref="{}product_announcement_date"/>
 *         &lt;element ref="{}product_release_date"/>
 *         &lt;element ref="{}web_release_date"/>
 *         &lt;element ref="{}i_chronicle_id"/>
 *         &lt;element ref="{}content_topic_details"/>
 *         &lt;element ref="{}document_type_details"/>
 *         &lt;element ref="{}environment_details"/>
 *         &lt;element ref="{}environments"/>
 *         &lt;element ref="{}issue_numbers"/>
 *         &lt;element ref="{}main_component_details"/>
 *         &lt;element ref="{}minor_component1_details"/>
 *         &lt;element ref="{}minor_component2_details"/>
 *         &lt;element ref="{}product_function_details"/>
 *         &lt;element ref="{}product_levels"/>
 *         &lt;element ref="{}serial_number_beginnings"/>
 *         &lt;element ref="{}serial_number_endings"/>
 *         &lt;element ref="{}serial_number_products"/>
 *         &lt;element ref="{}symptom_details"/>
 *         &lt;element ref="{}user_task_details"/>
 *         &lt;element ref="{}authors"/>
 *         &lt;element ref="{}faq_regions"/>
 *         &lt;element ref="{}publication_destinations"/>
 *         &lt;element ref="{}regions"/>
 *         &lt;element ref="{}esso_regions"/>
 *         &lt;element ref="{}search_keywords"/>
 *         &lt;element ref="{}software_groups"/>
 *         &lt;element ref="{}operating_system_groups"/>
 *         &lt;element ref="{}content_type"/>
 *         &lt;element ref="{}language_label"/>
 *         &lt;element ref="{}action_required"/>
 *         &lt;element ref="{}collection_valid_flag"/>
 *         &lt;element ref="{}information_source"/>
 *         &lt;element ref="{}publication_code"/>
 *         &lt;element ref="{}cmg_acronym"/>
 *         &lt;element ref="{}cmg_feedback_address"/>
 *         &lt;element ref="{}full_title"/>
 *         &lt;element ref="{}planned_public_date"/>
 *         &lt;element ref="{}master_object_name"/>
 *         &lt;element ref="{}custom_product_groups"/>
 *         &lt;element ref="{}faq_products"/>
 *         &lt;element ref="{}faq_custom_product_groups"/>
 *         &lt;element ref="{}joint_product_collections"/>
 *         &lt;element ref="{}project_name"/>
 *         &lt;element ref="{}extra_properties"/>
 *         &lt;element ref="{}file_name"/>
 *         &lt;element ref="{}components"/>
 *         &lt;element ref="{}failure_code"/>
 *         &lt;element ref="{}biz_defined_properties"/>
 *         &lt;element ref="{}col_content_associations"/>
 *         &lt;element ref="{}doc_content_associations"/>
 *         &lt;element ref="{}mdo_parent_ids"/>
 *         &lt;element ref="{}has_valid_products"/>
 *         &lt;element ref="{}content_version_date"/>
 *         &lt;element ref="{}valid_flag"/>
 *         &lt;element ref="{}clean_content_flag"/>
 *         &lt;element ref="{}object_name"/>
 *         &lt;element ref="{}col_id"/>
 *         &lt;element ref="{}confidential_comment"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}disclosure_level"/>
 *         &lt;element ref="{}content_version"/>
 *         &lt;element ref="{}dpi_resolution"/>
 *         &lt;element ref="{}issue_status"/>
 *         &lt;element ref="{}language_code"/>
 *         &lt;element ref="{}manual_action"/>
 *         &lt;element ref="{}creation_date"/>
 *         &lt;element ref="{}original_docid"/>
 *         &lt;element ref="{}original_filename"/>
 *         &lt;element ref="{}original_system"/>
 *         &lt;element ref="{}owner_name"/>
 *         &lt;element ref="{}pixel_height"/>
 *         &lt;element ref="{}pixel_width"/>
 *         &lt;element ref="{}publication_priority"/>
 *         &lt;element ref="{}document_class"/>
 *         &lt;element ref="{}recommended_action"/>
 *         &lt;element ref="{}review_date"/>
 *         &lt;element ref="{}service_program"/>
 *         &lt;element ref="{}short_title"/>
 *         &lt;element ref="{}top_issue_expiry"/>
 *         &lt;element ref="{}top_issue_expiry_date"/>
 *         &lt;element ref="{}wrapped_component_format"/>
 *         &lt;element ref="{}file_bytes"/>
 *         &lt;element ref="{}account_code"/>
 *         &lt;element ref="{}action_objective"/>
 *         &lt;element ref="{}content_topic"/>
 *         &lt;element ref="{}cost_per_issue"/>
 *         &lt;element ref="{}cost_per_unit"/>
 *         &lt;element ref="{}ia_identifier"/>
 *         &lt;element ref="{}labor_cost"/>
 *         &lt;element ref="{}labor_hours_paid"/>
 *         &lt;element ref="{}labor_minutes_paid"/>
 *         &lt;element ref="{}labor_rate_per_hour"/>
 *         &lt;element ref="{}main_component"/>
 *         &lt;element ref="{}material_cost_per_unit"/>
 *         &lt;element ref="{}minor_component1"/>
 *         &lt;element ref="{}minor_component2"/>
 *         &lt;element ref="{}parts_cost"/>
 *         &lt;element ref="{}parts_strategy"/>
 *         &lt;element ref="{}php_navigation"/>
 *         &lt;element ref="{}php_navigation_detail"/>
 *         &lt;element ref="{}product_category"/>
 *         &lt;element ref="{}product_division"/>
 *         &lt;element ref="{}product_function"/>
 *         &lt;element ref="{}service_inventory"/>
 *         &lt;element ref="{}service_type"/>
 *         &lt;element ref="{}software_topic"/>
 *         &lt;element ref="{}symptom"/>
 *         &lt;element ref="{}travel_cost"/>
 *         &lt;element ref="{}used_parts_action"/>
 *         &lt;element ref="{}user_task"/>
 *         &lt;element ref="{}action_expiry_date"/>
 *         &lt;element ref="{}action_start_date"/>
 *         &lt;element ref="{}effectivity_date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "companyInfo",
    "rObjectId",
    "priority",
    "products",
    "documentType",
    "versionLabel",
    "taxonomyCategorizations",
    "propertyUpdateDate",
    "contentUpdateDate",
    "activeFlag",
    "contentUpdateUser",
    "futureDisclosureDate",
    "futureDisclosureLevel",
    "isTranslationFlag",
    "lifecycleStateUpdateDate",
    "lifecycleStateUpdateUser",
    "propertyUpdateUser",
    "cmgName",
    "colMasterId",
    "collectionRefUpdateDate",
    "collectionUpdateDate",
    "collectionUpdateUser",
    "productAnnouncementDate",
    "productReleaseDate",
    "webReleaseDate",
    "iChronicleId",
    "contentTopicDetails",
    "documentTypeDetails",
    "environmentDetails",
    "environments",
    "issueNumbers",
    "mainComponentDetails",
    "minorComponent1Details",
    "minorComponent2Details",
    "productFunctionDetails",
    "productLevels",
    "serialNumberBeginnings",
    "serialNumberEndings",
    "serialNumberProducts",
    "symptomDetails",
    "userTaskDetails",
    "authors",
    "faqRegions",
    "publicationDestinations",
    "regions",
    "essoRegions",
    "searchKeywords",
    "softwareGroups",
    "operatingSystemGroups",
    "contentType",
    "languageLabel",
    "actionRequired",
    "collectionValidFlag",
    "informationSource",
    "publicationCode",
    "cmgAcronym",
    "cmgFeedbackAddress",
    "fullTitle",
    "plannedPublicDate",
    "masterObjectName",
    "customProductGroups",
    "faqProducts",
    "faqCustomProductGroups",
    "jointProductCollections",
    "projectName",
    "extraProperties",
    "fileName",
    "components",
    "failureCode",
    "bizDefinedProperties",
    "colContentAssociations",
    "docContentAssociations",
    "mdoParentIds",
    "hasValidProducts",
    "contentVersionDate",
    "validFlag",
    "cleanContentFlag",
    "objectName",
    "colId",
    "confidentialComment",
    "description",
    "disclosureLevel",
    "contentVersion",
    "dpiResolution",
    "issueStatus",
    "languageCode",
    "manualAction",
    "creationDate",
    "originalDocid",
    "originalFilename",
    "originalSystem",
    "ownerName",
    "pixelHeight",
    "pixelWidth",
    "publicationPriority",
    "documentClass",
    "recommendedAction",
    "reviewDate",
    "serviceProgram",
    "shortTitle",
    "topIssueExpiry",
    "topIssueExpiryDate",
    "wrappedComponentFormat",
    "fileBytes",
    "accountCode",
    "actionObjective",
    "contentTopic",
    "costPerIssue",
    "costPerUnit",
    "iaIdentifier",
    "laborCost",
    "laborHoursPaid",
    "laborMinutesPaid",
    "laborRatePerHour",
    "mainComponent",
    "materialCostPerUnit",
    "minorComponent1",
    "minorComponent2",
    "partsCost",
    "partsStrategy",
    "phpNavigation",
    "phpNavigationDetail",
    "productCategory",
    "productDivision",
    "productFunction",
    "serviceInventory",
    "serviceType",
    "softwareTopic",
    "symptom",
    "travelCost",
    "usedPartsAction",
    "userTask",
    "actionExpiryDate",
    "actionStartDate",
    "effectivityDate"
})
@XmlRootElement(name = "document")
public class Document {

    @XmlElement(name = "company_info", required = true)
    protected String companyInfo;
    @XmlElement(name = "r_object_id", required = true)
    protected String rObjectId;
    protected byte priority;
    @XmlElement(required = true)
    protected Products products;
    @XmlElement(name = "document_type", required = true)
    protected String documentType;
    @XmlElement(name = "version_label", required = true)
    protected BigDecimal versionLabel;
    @XmlElement(name = "taxonomy_categorizations", required = true)
    protected TaxonomyCategorizations taxonomyCategorizations;
    @XmlElement(name = "property_update_date", required = true)
    protected XMLGregorianCalendar propertyUpdateDate;
    @XmlElement(name = "content_update_date", required = true)
    protected XMLGregorianCalendar contentUpdateDate;
    @XmlElement(name = "active_flag")
    protected boolean activeFlag;
    @XmlElement(name = "content_update_user", required = true)
    protected String contentUpdateUser;
    @XmlElement(name = "future_disclosure_date", required = true)
    protected XMLGregorianCalendar futureDisclosureDate;
    @XmlElement(name = "future_disclosure_level", required = true)
    protected String futureDisclosureLevel;
    @XmlElement(name = "is_translation_flag")
    protected boolean isTranslationFlag;
    @XmlElement(name = "lifecycle_state_update_date", required = true)
    protected XMLGregorianCalendar lifecycleStateUpdateDate;
    @XmlElement(name = "lifecycle_state_update_user", required = true)
    protected String lifecycleStateUpdateUser;
    @XmlElement(name = "property_update_user", required = true)
    protected String propertyUpdateUser;
    @XmlElement(name = "cmg_name", required = true)
    protected String cmgName;
    @XmlElement(name = "col_master_id", required = true)
    protected String colMasterId;
    @XmlElement(name = "collection_ref_update_date", required = true)
    protected XMLGregorianCalendar collectionRefUpdateDate;
    @XmlElement(name = "collection_update_date", required = true)
    protected XMLGregorianCalendar collectionUpdateDate;
    @XmlElement(name = "collection_update_user", required = true)
    protected String collectionUpdateUser;
    @XmlElement(name = "product_announcement_date", required = true)
    protected XMLGregorianCalendar productAnnouncementDate;
    @XmlElement(name = "product_release_date", required = true)
    protected XMLGregorianCalendar productReleaseDate;
    @XmlElement(name = "web_release_date", required = true)
    protected XMLGregorianCalendar webReleaseDate;
    @XmlElement(name = "i_chronicle_id", required = true)
    protected String iChronicleId;
    @XmlElement(name = "content_topic_details", required = true)
    protected ContentTopicDetails contentTopicDetails;
    @XmlElement(name = "document_type_details", required = true)
    protected DocumentTypeDetails documentTypeDetails;
    @XmlElement(name = "environment_details", required = true)
    protected EnvironmentDetails environmentDetails;
    @XmlElement(required = true)
    protected Environments environments;
    @XmlElement(name = "issue_numbers", required = true)
    protected IssueNumbers issueNumbers;
    @XmlElement(name = "main_component_details", required = true)
    protected MainComponentDetails mainComponentDetails;
    @XmlElement(name = "minor_component1_details", required = true)
    protected MinorComponent1Details minorComponent1Details;
    @XmlElement(name = "minor_component2_details", required = true)
    protected MinorComponent2Details minorComponent2Details;
    @XmlElement(name = "product_function_details", required = true)
    protected ProductFunctionDetails productFunctionDetails;
    @XmlElement(name = "product_levels", required = true)
    protected ProductLevels productLevels;
    @XmlElement(name = "serial_number_beginnings", required = true)
    protected SerialNumberBeginnings serialNumberBeginnings;
    @XmlElement(name = "serial_number_endings", required = true)
    protected SerialNumberEndings serialNumberEndings;
    @XmlElement(name = "serial_number_products", required = true)
    protected SerialNumberProducts serialNumberProducts;
    @XmlElement(name = "symptom_details", required = true)
    protected SymptomDetails symptomDetails;
    @XmlElement(name = "user_task_details", required = true)
    protected UserTaskDetails userTaskDetails;
    @XmlElement(required = true)
    protected Authors authors;
    @XmlElement(name = "faq_regions", required = true)
    protected FaqRegions faqRegions;
    @XmlElement(name = "publication_destinations", required = true)
    protected PublicationDestinations publicationDestinations;
    @XmlElement(required = true)
    protected Regions regions;
    @XmlElement(name = "esso_regions", required = true)
    protected EssoRegions essoRegions;
    @XmlElement(name = "search_keywords", required = true)
    protected SearchKeywords searchKeywords;
    @XmlElement(name = "software_groups", required = true)
    protected SoftwareGroups softwareGroups;
    @XmlElement(name = "operating_system_groups", required = true)
    protected OperatingSystemGroups operatingSystemGroups;
    @XmlElement(name = "content_type", required = true)
    protected String contentType;
    @XmlElement(name = "language_label", required = true)
    protected String languageLabel;
    @XmlElement(name = "action_required")
    protected boolean actionRequired;
    @XmlElement(name = "collection_valid_flag")
    protected boolean collectionValidFlag;
    @XmlElement(name = "information_source", required = true)
    protected String informationSource;
    @XmlElement(name = "publication_code", required = true)
    protected String publicationCode;
    @XmlElement(name = "cmg_acronym", required = true)
    protected String cmgAcronym;
    @XmlElement(name = "cmg_feedback_address", required = true)
    protected String cmgFeedbackAddress;
    @XmlElement(name = "full_title", required = true)
    protected FullTitle fullTitle;
    @XmlElement(name = "planned_public_date", required = true)
    protected XMLGregorianCalendar plannedPublicDate;
    @XmlElement(name = "master_object_name", required = true)
    protected String masterObjectName;
    @XmlElement(name = "custom_product_groups", required = true)
    protected CustomProductGroups customProductGroups;
    @XmlElement(name = "faq_products", required = true)
    protected FaqProducts faqProducts;
    @XmlElement(name = "faq_custom_product_groups", required = true)
    protected FaqCustomProductGroups faqCustomProductGroups;
    @XmlElement(name = "joint_product_collections", required = true)
    protected JointProductCollections jointProductCollections;
    @XmlElement(name = "project_name", required = true)
    protected String projectName;
    @XmlElement(name = "extra_properties", required = true)
    protected ExtraProperties extraProperties;
    @XmlElement(name = "file_name", required = true)
    protected String fileName;
    @XmlElement(required = true)
    protected Components components;
    @XmlElement(name = "failure_code", required = true)
    protected String failureCode;
    @XmlElement(name = "biz_defined_properties", required = true)
    protected BizDefinedProperties bizDefinedProperties;
    @XmlElement(name = "col_content_associations", required = true)
    protected ColContentAssociations colContentAssociations;
    @XmlElement(name = "doc_content_associations", required = true)
    protected DocContentAssociations docContentAssociations;
    @XmlElement(name = "mdo_parent_ids", required = true)
    protected MdoParentIds mdoParentIds;
    @XmlElement(name = "has_valid_products")
    protected boolean hasValidProducts;
    @XmlElement(name = "content_version_date", required = true)
    protected XMLGregorianCalendar contentVersionDate;
    @XmlElement(name = "valid_flag")
    protected boolean validFlag;
    @XmlElement(name = "clean_content_flag")
    protected boolean cleanContentFlag;
    @XmlElement(name = "object_name", required = true)
    protected String objectName;
    @XmlElement(name = "col_id", required = true)
    protected String colId;
    @XmlElement(name = "confidential_comment", required = true)
    protected String confidentialComment;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "disclosure_level", required = true)
    protected String disclosureLevel;
    @XmlElement(name = "content_version", required = true)
    protected BigDecimal contentVersion;
    @XmlElement(name = "dpi_resolution")
    protected int dpiResolution;
    @XmlElement(name = "issue_status", required = true)
    protected String issueStatus;
    @XmlElement(name = "language_code", required = true)
    protected String languageCode;
    @XmlElement(name = "manual_action", required = true)
    protected String manualAction;
    @XmlElement(name = "creation_date", required = true)
    protected XMLGregorianCalendar creationDate;
    @XmlElement(name = "original_docid", required = true)
    protected String originalDocid;
    @XmlElement(name = "original_filename", required = true)
    protected String originalFilename;
    @XmlElement(name = "original_system", required = true)
    protected String originalSystem;
    @XmlElement(name = "owner_name", required = true)
    protected String ownerName;
    @XmlElement(name = "pixel_height", required = true)
    protected BigInteger pixelHeight;
    @XmlElement(name = "pixel_width", required = true)
    protected BigInteger pixelWidth;
    @XmlElement(name = "publication_priority", required = true)
    protected String publicationPriority;
    @XmlElement(name = "document_class", required = true)
    protected String documentClass;
    @XmlElement(name = "recommended_action", required = true)
    protected String recommendedAction;
    @XmlElement(name = "review_date", required = true)
    protected XMLGregorianCalendar reviewDate;
    @XmlElement(name = "service_program", required = true)
    protected String serviceProgram;
    @XmlElement(name = "short_title", required = true)
    protected String shortTitle;
    @XmlElement(name = "top_issue_expiry", required = true)
    protected String topIssueExpiry;
    @XmlElement(name = "top_issue_expiry_date", required = true)
    protected XMLGregorianCalendar topIssueExpiryDate;
    @XmlElement(name = "wrapped_component_format", required = true)
    protected String wrappedComponentFormat;
    @XmlElement(name = "file_bytes")
    protected long fileBytes;
    @XmlElement(name = "account_code", required = true)
    protected String accountCode;
    @XmlElement(name = "action_objective", required = true)
    protected String actionObjective;
    @XmlElement(name = "content_topic", required = true)
    protected String contentTopic;
    @XmlElement(name = "cost_per_issue", required = true)
    protected String costPerIssue;
    @XmlElement(name = "cost_per_unit", required = true)
    protected String costPerUnit;
    @XmlElement(name = "ia_identifier", required = true)
    protected String iaIdentifier;
    @XmlElement(name = "labor_cost", required = true)
    protected String laborCost;
    @XmlElement(name = "labor_hours_paid", required = true)
    protected String laborHoursPaid;
    @XmlElement(name = "labor_minutes_paid", required = true)
    protected String laborMinutesPaid;
    @XmlElement(name = "labor_rate_per_hour", required = true)
    protected String laborRatePerHour;
    @XmlElement(name = "main_component", required = true)
    protected String mainComponent;
    @XmlElement(name = "material_cost_per_unit", required = true)
    protected String materialCostPerUnit;
    @XmlElement(name = "minor_component1", required = true)
    protected String minorComponent1;
    @XmlElement(name = "minor_component2", required = true)
    protected String minorComponent2;
    @XmlElement(name = "parts_cost", required = true)
    protected String partsCost;
    @XmlElement(name = "parts_strategy", required = true)
    protected String partsStrategy;
    @XmlElement(name = "php_navigation", required = true)
    protected String phpNavigation;
    @XmlElement(name = "php_navigation_detail", required = true)
    protected String phpNavigationDetail;
    @XmlElement(name = "product_category", required = true)
    protected String productCategory;
    @XmlElement(name = "product_division", required = true)
    protected String productDivision;
    @XmlElement(name = "product_function", required = true)
    protected String productFunction;
    @XmlElement(name = "service_inventory", required = true)
    protected String serviceInventory;
    @XmlElement(name = "service_type", required = true)
    protected String serviceType;
    @XmlElement(name = "software_topic", required = true)
    protected String softwareTopic;
    @XmlElement(required = true)
    protected String symptom;
    @XmlElement(name = "travel_cost", required = true)
    protected String travelCost;
    @XmlElement(name = "used_parts_action", required = true)
    protected String usedPartsAction;
    @XmlElement(name = "user_task", required = true)
    protected String userTask;
    @XmlElement(name = "action_expiry_date", required = true)
    protected XMLGregorianCalendar actionExpiryDate;
    @XmlElement(name = "action_start_date", required = true)
    protected XMLGregorianCalendar actionStartDate;
    @XmlElement(name = "effectivity_date", required = true)
    protected XMLGregorianCalendar effectivityDate;

    /**
     * Gets the value of the companyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyInfo() {
        return companyInfo;
    }

    /**
     * Sets the value of the companyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyInfo(String value) {
        this.companyInfo = value;
    }

    /**
     * Gets the value of the rObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRObjectId() {
        return rObjectId;
    }

    /**
     * Sets the value of the rObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRObjectId(String value) {
        this.rObjectId = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public byte getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(byte value) {
        this.priority = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link Products }
     *     
     */
    public Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link Products }
     *     
     */
    public void setProducts(Products value) {
        this.products = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the versionLabel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersionLabel() {
        return versionLabel;
    }

    /**
     * Sets the value of the versionLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersionLabel(BigDecimal value) {
        this.versionLabel = value;
    }

    /**
     * Gets the value of the taxonomyCategorizations property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonomyCategorizations }
     *     
     */
    public TaxonomyCategorizations getTaxonomyCategorizations() {
        return taxonomyCategorizations;
    }

    /**
     * Sets the value of the taxonomyCategorizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonomyCategorizations }
     *     
     */
    public void setTaxonomyCategorizations(TaxonomyCategorizations value) {
        this.taxonomyCategorizations = value;
    }

    /**
     * Gets the value of the propertyUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPropertyUpdateDate() {
        return propertyUpdateDate;
    }

    /**
     * Sets the value of the propertyUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPropertyUpdateDate(XMLGregorianCalendar value) {
        this.propertyUpdateDate = value;
    }

    /**
     * Gets the value of the contentUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContentUpdateDate() {
        return contentUpdateDate;
    }

    /**
     * Sets the value of the contentUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContentUpdateDate(XMLGregorianCalendar value) {
        this.contentUpdateDate = value;
    }

    /**
     * Gets the value of the activeFlag property.
     * 
     */
    public boolean isActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     */
    public void setActiveFlag(boolean value) {
        this.activeFlag = value;
    }

    /**
     * Gets the value of the contentUpdateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentUpdateUser() {
        return contentUpdateUser;
    }

    /**
     * Sets the value of the contentUpdateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentUpdateUser(String value) {
        this.contentUpdateUser = value;
    }

    /**
     * Gets the value of the futureDisclosureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFutureDisclosureDate() {
        return futureDisclosureDate;
    }

    /**
     * Sets the value of the futureDisclosureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFutureDisclosureDate(XMLGregorianCalendar value) {
        this.futureDisclosureDate = value;
    }

    /**
     * Gets the value of the futureDisclosureLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFutureDisclosureLevel() {
        return futureDisclosureLevel;
    }

    /**
     * Sets the value of the futureDisclosureLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFutureDisclosureLevel(String value) {
        this.futureDisclosureLevel = value;
    }

    /**
     * Gets the value of the isTranslationFlag property.
     * 
     */
    public boolean isIsTranslationFlag() {
        return isTranslationFlag;
    }

    /**
     * Sets the value of the isTranslationFlag property.
     * 
     */
    public void setIsTranslationFlag(boolean value) {
        this.isTranslationFlag = value;
    }

    /**
     * Gets the value of the lifecycleStateUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLifecycleStateUpdateDate() {
        return lifecycleStateUpdateDate;
    }

    /**
     * Sets the value of the lifecycleStateUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLifecycleStateUpdateDate(XMLGregorianCalendar value) {
        this.lifecycleStateUpdateDate = value;
    }

    /**
     * Gets the value of the lifecycleStateUpdateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifecycleStateUpdateUser() {
        return lifecycleStateUpdateUser;
    }

    /**
     * Sets the value of the lifecycleStateUpdateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifecycleStateUpdateUser(String value) {
        this.lifecycleStateUpdateUser = value;
    }

    /**
     * Gets the value of the propertyUpdateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyUpdateUser() {
        return propertyUpdateUser;
    }

    /**
     * Sets the value of the propertyUpdateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyUpdateUser(String value) {
        this.propertyUpdateUser = value;
    }

    /**
     * Gets the value of the cmgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmgName() {
        return cmgName;
    }

    /**
     * Sets the value of the cmgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmgName(String value) {
        this.cmgName = value;
    }

    /**
     * Gets the value of the colMasterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColMasterId() {
        return colMasterId;
    }

    /**
     * Sets the value of the colMasterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColMasterId(String value) {
        this.colMasterId = value;
    }

    /**
     * Gets the value of the collectionRefUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCollectionRefUpdateDate() {
        return collectionRefUpdateDate;
    }

    /**
     * Sets the value of the collectionRefUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCollectionRefUpdateDate(XMLGregorianCalendar value) {
        this.collectionRefUpdateDate = value;
    }

    /**
     * Gets the value of the collectionUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCollectionUpdateDate() {
        return collectionUpdateDate;
    }

    /**
     * Sets the value of the collectionUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCollectionUpdateDate(XMLGregorianCalendar value) {
        this.collectionUpdateDate = value;
    }

    /**
     * Gets the value of the collectionUpdateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionUpdateUser() {
        return collectionUpdateUser;
    }

    /**
     * Sets the value of the collectionUpdateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionUpdateUser(String value) {
        this.collectionUpdateUser = value;
    }

    /**
     * Gets the value of the productAnnouncementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProductAnnouncementDate() {
        return productAnnouncementDate;
    }

    /**
     * Sets the value of the productAnnouncementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProductAnnouncementDate(XMLGregorianCalendar value) {
        this.productAnnouncementDate = value;
    }

    /**
     * Gets the value of the productReleaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProductReleaseDate() {
        return productReleaseDate;
    }

    /**
     * Sets the value of the productReleaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProductReleaseDate(XMLGregorianCalendar value) {
        this.productReleaseDate = value;
    }

    /**
     * Gets the value of the webReleaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWebReleaseDate() {
        return webReleaseDate;
    }

    /**
     * Sets the value of the webReleaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWebReleaseDate(XMLGregorianCalendar value) {
        this.webReleaseDate = value;
    }

    /**
     * Gets the value of the iChronicleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIChronicleId() {
        return iChronicleId;
    }

    /**
     * Sets the value of the iChronicleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIChronicleId(String value) {
        this.iChronicleId = value;
    }

    /**
     * Gets the value of the contentTopicDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContentTopicDetails }
     *     
     */
    public ContentTopicDetails getContentTopicDetails() {
        return contentTopicDetails;
    }

    /**
     * Sets the value of the contentTopicDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentTopicDetails }
     *     
     */
    public void setContentTopicDetails(ContentTopicDetails value) {
        this.contentTopicDetails = value;
    }

    /**
     * Gets the value of the documentTypeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentTypeDetails }
     *     
     */
    public DocumentTypeDetails getDocumentTypeDetails() {
        return documentTypeDetails;
    }

    /**
     * Sets the value of the documentTypeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentTypeDetails }
     *     
     */
    public void setDocumentTypeDetails(DocumentTypeDetails value) {
        this.documentTypeDetails = value;
    }

    /**
     * Gets the value of the environmentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EnvironmentDetails }
     *     
     */
    public EnvironmentDetails getEnvironmentDetails() {
        return environmentDetails;
    }

    /**
     * Sets the value of the environmentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvironmentDetails }
     *     
     */
    public void setEnvironmentDetails(EnvironmentDetails value) {
        this.environmentDetails = value;
    }

    /**
     * Gets the value of the environments property.
     * 
     * @return
     *     possible object is
     *     {@link Environments }
     *     
     */
    public Environments getEnvironments() {
        return environments;
    }

    /**
     * Sets the value of the environments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Environments }
     *     
     */
    public void setEnvironments(Environments value) {
        this.environments = value;
    }

    /**
     * Gets the value of the issueNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link IssueNumbers }
     *     
     */
    public IssueNumbers getIssueNumbers() {
        return issueNumbers;
    }

    /**
     * Sets the value of the issueNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueNumbers }
     *     
     */
    public void setIssueNumbers(IssueNumbers value) {
        this.issueNumbers = value;
    }

    /**
     * Gets the value of the mainComponentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MainComponentDetails }
     *     
     */
    public MainComponentDetails getMainComponentDetails() {
        return mainComponentDetails;
    }

    /**
     * Sets the value of the mainComponentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainComponentDetails }
     *     
     */
    public void setMainComponentDetails(MainComponentDetails value) {
        this.mainComponentDetails = value;
    }

    /**
     * Gets the value of the minorComponent1Details property.
     * 
     * @return
     *     possible object is
     *     {@link MinorComponent1Details }
     *     
     */
    public MinorComponent1Details getMinorComponent1Details() {
        return minorComponent1Details;
    }

    /**
     * Sets the value of the minorComponent1Details property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinorComponent1Details }
     *     
     */
    public void setMinorComponent1Details(MinorComponent1Details value) {
        this.minorComponent1Details = value;
    }

    /**
     * Gets the value of the minorComponent2Details property.
     * 
     * @return
     *     possible object is
     *     {@link MinorComponent2Details }
     *     
     */
    public MinorComponent2Details getMinorComponent2Details() {
        return minorComponent2Details;
    }

    /**
     * Sets the value of the minorComponent2Details property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinorComponent2Details }
     *     
     */
    public void setMinorComponent2Details(MinorComponent2Details value) {
        this.minorComponent2Details = value;
    }

    /**
     * Gets the value of the productFunctionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFunctionDetails }
     *     
     */
    public ProductFunctionDetails getProductFunctionDetails() {
        return productFunctionDetails;
    }

    /**
     * Sets the value of the productFunctionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFunctionDetails }
     *     
     */
    public void setProductFunctionDetails(ProductFunctionDetails value) {
        this.productFunctionDetails = value;
    }

    /**
     * Gets the value of the productLevels property.
     * 
     * @return
     *     possible object is
     *     {@link ProductLevels }
     *     
     */
    public ProductLevels getProductLevels() {
        return productLevels;
    }

    /**
     * Sets the value of the productLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductLevels }
     *     
     */
    public void setProductLevels(ProductLevels value) {
        this.productLevels = value;
    }

    /**
     * Gets the value of the serialNumberBeginnings property.
     * 
     * @return
     *     possible object is
     *     {@link SerialNumberBeginnings }
     *     
     */
    public SerialNumberBeginnings getSerialNumberBeginnings() {
        return serialNumberBeginnings;
    }

    /**
     * Sets the value of the serialNumberBeginnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialNumberBeginnings }
     *     
     */
    public void setSerialNumberBeginnings(SerialNumberBeginnings value) {
        this.serialNumberBeginnings = value;
    }

    /**
     * Gets the value of the serialNumberEndings property.
     * 
     * @return
     *     possible object is
     *     {@link SerialNumberEndings }
     *     
     */
    public SerialNumberEndings getSerialNumberEndings() {
        return serialNumberEndings;
    }

    /**
     * Sets the value of the serialNumberEndings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialNumberEndings }
     *     
     */
    public void setSerialNumberEndings(SerialNumberEndings value) {
        this.serialNumberEndings = value;
    }

    /**
     * Gets the value of the serialNumberProducts property.
     * 
     * @return
     *     possible object is
     *     {@link SerialNumberProducts }
     *     
     */
    public SerialNumberProducts getSerialNumberProducts() {
        return serialNumberProducts;
    }

    /**
     * Sets the value of the serialNumberProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialNumberProducts }
     *     
     */
    public void setSerialNumberProducts(SerialNumberProducts value) {
        this.serialNumberProducts = value;
    }

    /**
     * Gets the value of the symptomDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SymptomDetails }
     *     
     */
    public SymptomDetails getSymptomDetails() {
        return symptomDetails;
    }

    /**
     * Sets the value of the symptomDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SymptomDetails }
     *     
     */
    public void setSymptomDetails(SymptomDetails value) {
        this.symptomDetails = value;
    }

    /**
     * Gets the value of the userTaskDetails property.
     * 
     * @return
     *     possible object is
     *     {@link UserTaskDetails }
     *     
     */
    public UserTaskDetails getUserTaskDetails() {
        return userTaskDetails;
    }

    /**
     * Sets the value of the userTaskDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserTaskDetails }
     *     
     */
    public void setUserTaskDetails(UserTaskDetails value) {
        this.userTaskDetails = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link Authors }
     *     
     */
    public Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authors }
     *     
     */
    public void setAuthors(Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the faqRegions property.
     * 
     * @return
     *     possible object is
     *     {@link FaqRegions }
     *     
     */
    public FaqRegions getFaqRegions() {
        return faqRegions;
    }

    /**
     * Sets the value of the faqRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaqRegions }
     *     
     */
    public void setFaqRegions(FaqRegions value) {
        this.faqRegions = value;
    }

    /**
     * Gets the value of the publicationDestinations property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationDestinations }
     *     
     */
    public PublicationDestinations getPublicationDestinations() {
        return publicationDestinations;
    }

    /**
     * Sets the value of the publicationDestinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationDestinations }
     *     
     */
    public void setPublicationDestinations(PublicationDestinations value) {
        this.publicationDestinations = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link Regions }
     *     
     */
    public Regions getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regions }
     *     
     */
    public void setRegions(Regions value) {
        this.regions = value;
    }

    /**
     * Gets the value of the essoRegions property.
     * 
     * @return
     *     possible object is
     *     {@link EssoRegions }
     *     
     */
    public EssoRegions getEssoRegions() {
        return essoRegions;
    }

    /**
     * Sets the value of the essoRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link EssoRegions }
     *     
     */
    public void setEssoRegions(EssoRegions value) {
        this.essoRegions = value;
    }

    /**
     * Gets the value of the searchKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link SearchKeywords }
     *     
     */
    public SearchKeywords getSearchKeywords() {
        return searchKeywords;
    }

    /**
     * Sets the value of the searchKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchKeywords }
     *     
     */
    public void setSearchKeywords(SearchKeywords value) {
        this.searchKeywords = value;
    }

    /**
     * Gets the value of the softwareGroups property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareGroups }
     *     
     */
    public SoftwareGroups getSoftwareGroups() {
        return softwareGroups;
    }

    /**
     * Sets the value of the softwareGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareGroups }
     *     
     */
    public void setSoftwareGroups(SoftwareGroups value) {
        this.softwareGroups = value;
    }

    /**
     * Gets the value of the operatingSystemGroups property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingSystemGroups }
     *     
     */
    public OperatingSystemGroups getOperatingSystemGroups() {
        return operatingSystemGroups;
    }

    /**
     * Sets the value of the operatingSystemGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingSystemGroups }
     *     
     */
    public void setOperatingSystemGroups(OperatingSystemGroups value) {
        this.operatingSystemGroups = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the languageLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageLabel() {
        return languageLabel;
    }

    /**
     * Sets the value of the languageLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageLabel(String value) {
        this.languageLabel = value;
    }

    /**
     * Gets the value of the actionRequired property.
     * 
     */
    public boolean isActionRequired() {
        return actionRequired;
    }

    /**
     * Sets the value of the actionRequired property.
     * 
     */
    public void setActionRequired(boolean value) {
        this.actionRequired = value;
    }

    /**
     * Gets the value of the collectionValidFlag property.
     * 
     */
    public boolean isCollectionValidFlag() {
        return collectionValidFlag;
    }

    /**
     * Sets the value of the collectionValidFlag property.
     * 
     */
    public void setCollectionValidFlag(boolean value) {
        this.collectionValidFlag = value;
    }

    /**
     * Gets the value of the informationSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationSource() {
        return informationSource;
    }

    /**
     * Sets the value of the informationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationSource(String value) {
        this.informationSource = value;
    }

    /**
     * Gets the value of the publicationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationCode() {
        return publicationCode;
    }

    /**
     * Sets the value of the publicationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationCode(String value) {
        this.publicationCode = value;
    }

    /**
     * Gets the value of the cmgAcronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmgAcronym() {
        return cmgAcronym;
    }

    /**
     * Sets the value of the cmgAcronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmgAcronym(String value) {
        this.cmgAcronym = value;
    }

    /**
     * Gets the value of the cmgFeedbackAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmgFeedbackAddress() {
        return cmgFeedbackAddress;
    }

    /**
     * Sets the value of the cmgFeedbackAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmgFeedbackAddress(String value) {
        this.cmgFeedbackAddress = value;
    }

    /**
     * Gets the value of the fullTitle property.
     * 
     * @return
     *     possible object is
     *     {@link FullTitle }
     *     
     */
    public FullTitle getFullTitle() {
        return fullTitle;
    }

    /**
     * Sets the value of the fullTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullTitle }
     *     
     */
    public void setFullTitle(FullTitle value) {
        this.fullTitle = value;
    }

    /**
     * Gets the value of the plannedPublicDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlannedPublicDate() {
        return plannedPublicDate;
    }

    /**
     * Sets the value of the plannedPublicDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlannedPublicDate(XMLGregorianCalendar value) {
        this.plannedPublicDate = value;
    }

    /**
     * Gets the value of the masterObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterObjectName() {
        return masterObjectName;
    }

    /**
     * Sets the value of the masterObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterObjectName(String value) {
        this.masterObjectName = value;
    }

    /**
     * Gets the value of the customProductGroups property.
     * 
     * @return
     *     possible object is
     *     {@link CustomProductGroups }
     *     
     */
    public CustomProductGroups getCustomProductGroups() {
        return customProductGroups;
    }

    /**
     * Sets the value of the customProductGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomProductGroups }
     *     
     */
    public void setCustomProductGroups(CustomProductGroups value) {
        this.customProductGroups = value;
    }

    /**
     * Gets the value of the faqProducts property.
     * 
     * @return
     *     possible object is
     *     {@link FaqProducts }
     *     
     */
    public FaqProducts getFaqProducts() {
        return faqProducts;
    }

    /**
     * Sets the value of the faqProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaqProducts }
     *     
     */
    public void setFaqProducts(FaqProducts value) {
        this.faqProducts = value;
    }

    /**
     * Gets the value of the faqCustomProductGroups property.
     * 
     * @return
     *     possible object is
     *     {@link FaqCustomProductGroups }
     *     
     */
    public FaqCustomProductGroups getFaqCustomProductGroups() {
        return faqCustomProductGroups;
    }

    /**
     * Sets the value of the faqCustomProductGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaqCustomProductGroups }
     *     
     */
    public void setFaqCustomProductGroups(FaqCustomProductGroups value) {
        this.faqCustomProductGroups = value;
    }

    /**
     * Gets the value of the jointProductCollections property.
     * 
     * @return
     *     possible object is
     *     {@link JointProductCollections }
     *     
     */
    public JointProductCollections getJointProductCollections() {
        return jointProductCollections;
    }

    /**
     * Sets the value of the jointProductCollections property.
     * 
     * @param value
     *     allowed object is
     *     {@link JointProductCollections }
     *     
     */
    public void setJointProductCollections(JointProductCollections value) {
        this.jointProductCollections = value;
    }

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the extraProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraProperties }
     *     
     */
    public ExtraProperties getExtraProperties() {
        return extraProperties;
    }

    /**
     * Sets the value of the extraProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraProperties }
     *     
     */
    public void setExtraProperties(ExtraProperties value) {
        this.extraProperties = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link Components }
     *     
     */
    public Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link Components }
     *     
     */
    public void setComponents(Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the failureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureCode() {
        return failureCode;
    }

    /**
     * Sets the value of the failureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureCode(String value) {
        this.failureCode = value;
    }

    /**
     * Gets the value of the bizDefinedProperties property.
     * 
     * @return
     *     possible object is
     *     {@link BizDefinedProperties }
     *     
     */
    public BizDefinedProperties getBizDefinedProperties() {
        return bizDefinedProperties;
    }

    /**
     * Sets the value of the bizDefinedProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link BizDefinedProperties }
     *     
     */
    public void setBizDefinedProperties(BizDefinedProperties value) {
        this.bizDefinedProperties = value;
    }

    /**
     * Gets the value of the colContentAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link ColContentAssociations }
     *     
     */
    public ColContentAssociations getColContentAssociations() {
        return colContentAssociations;
    }

    /**
     * Sets the value of the colContentAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColContentAssociations }
     *     
     */
    public void setColContentAssociations(ColContentAssociations value) {
        this.colContentAssociations = value;
    }

    /**
     * Gets the value of the docContentAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link DocContentAssociations }
     *     
     */
    public DocContentAssociations getDocContentAssociations() {
        return docContentAssociations;
    }

    /**
     * Sets the value of the docContentAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocContentAssociations }
     *     
     */
    public void setDocContentAssociations(DocContentAssociations value) {
        this.docContentAssociations = value;
    }

    /**
     * Gets the value of the mdoParentIds property.
     * 
     * @return
     *     possible object is
     *     {@link MdoParentIds }
     *     
     */
    public MdoParentIds getMdoParentIds() {
        return mdoParentIds;
    }

    /**
     * Sets the value of the mdoParentIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link MdoParentIds }
     *     
     */
    public void setMdoParentIds(MdoParentIds value) {
        this.mdoParentIds = value;
    }

    /**
     * Gets the value of the hasValidProducts property.
     * 
     */
    public boolean isHasValidProducts() {
        return hasValidProducts;
    }

    /**
     * Sets the value of the hasValidProducts property.
     * 
     */
    public void setHasValidProducts(boolean value) {
        this.hasValidProducts = value;
    }

    /**
     * Gets the value of the contentVersionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContentVersionDate() {
        return contentVersionDate;
    }

    /**
     * Sets the value of the contentVersionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContentVersionDate(XMLGregorianCalendar value) {
        this.contentVersionDate = value;
    }

    /**
     * Gets the value of the validFlag property.
     * 
     */
    public boolean isValidFlag() {
        return validFlag;
    }

    /**
     * Sets the value of the validFlag property.
     * 
     */
    public void setValidFlag(boolean value) {
        this.validFlag = value;
    }

    /**
     * Gets the value of the cleanContentFlag property.
     * 
     */
    public boolean isCleanContentFlag() {
        return cleanContentFlag;
    }

    /**
     * Sets the value of the cleanContentFlag property.
     * 
     */
    public void setCleanContentFlag(boolean value) {
        this.cleanContentFlag = value;
    }

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the colId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColId() {
        return colId;
    }

    /**
     * Sets the value of the colId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColId(String value) {
        this.colId = value;
    }

    /**
     * Gets the value of the confidentialComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfidentialComment() {
        return confidentialComment;
    }

    /**
     * Sets the value of the confidentialComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfidentialComment(String value) {
        this.confidentialComment = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the disclosureLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosureLevel() {
        return disclosureLevel;
    }

    /**
     * Sets the value of the disclosureLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosureLevel(String value) {
        this.disclosureLevel = value;
    }

    /**
     * Gets the value of the contentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getContentVersion() {
        return contentVersion;
    }

    /**
     * Sets the value of the contentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setContentVersion(BigDecimal value) {
        this.contentVersion = value;
    }

    /**
     * Gets the value of the dpiResolution property.
     * 
     */
    public int getDpiResolution() {
        return dpiResolution;
    }

    /**
     * Sets the value of the dpiResolution property.
     * 
     */
    public void setDpiResolution(int value) {
        this.dpiResolution = value;
    }

    /**
     * Gets the value of the issueStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueStatus() {
        return issueStatus;
    }

    /**
     * Sets the value of the issueStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueStatus(String value) {
        this.issueStatus = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the manualAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManualAction() {
        return manualAction;
    }

    /**
     * Sets the value of the manualAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManualAction(String value) {
        this.manualAction = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the originalDocid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalDocid() {
        return originalDocid;
    }

    /**
     * Sets the value of the originalDocid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalDocid(String value) {
        this.originalDocid = value;
    }

    /**
     * Gets the value of the originalFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalFilename() {
        return originalFilename;
    }

    /**
     * Sets the value of the originalFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalFilename(String value) {
        this.originalFilename = value;
    }

    /**
     * Gets the value of the originalSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalSystem() {
        return originalSystem;
    }

    /**
     * Sets the value of the originalSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalSystem(String value) {
        this.originalSystem = value;
    }

    /**
     * Gets the value of the ownerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * Sets the value of the ownerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerName(String value) {
        this.ownerName = value;
    }

    /**
     * Gets the value of the pixelHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPixelHeight() {
        return pixelHeight;
    }

    /**
     * Sets the value of the pixelHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPixelHeight(BigInteger value) {
        this.pixelHeight = value;
    }

    /**
     * Gets the value of the pixelWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPixelWidth() {
        return pixelWidth;
    }

    /**
     * Sets the value of the pixelWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPixelWidth(BigInteger value) {
        this.pixelWidth = value;
    }

    /**
     * Gets the value of the publicationPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationPriority() {
        return publicationPriority;
    }

    /**
     * Sets the value of the publicationPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationPriority(String value) {
        this.publicationPriority = value;
    }

    /**
     * Gets the value of the documentClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentClass() {
        return documentClass;
    }

    /**
     * Sets the value of the documentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentClass(String value) {
        this.documentClass = value;
    }

    /**
     * Gets the value of the recommendedAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendedAction() {
        return recommendedAction;
    }

    /**
     * Sets the value of the recommendedAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendedAction(String value) {
        this.recommendedAction = value;
    }

    /**
     * Gets the value of the reviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReviewDate() {
        return reviewDate;
    }

    /**
     * Sets the value of the reviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReviewDate(XMLGregorianCalendar value) {
        this.reviewDate = value;
    }

    /**
     * Gets the value of the serviceProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProgram() {
        return serviceProgram;
    }

    /**
     * Sets the value of the serviceProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProgram(String value) {
        this.serviceProgram = value;
    }

    /**
     * Gets the value of the shortTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * Sets the value of the shortTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortTitle(String value) {
        this.shortTitle = value;
    }

    /**
     * Gets the value of the topIssueExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopIssueExpiry() {
        return topIssueExpiry;
    }

    /**
     * Sets the value of the topIssueExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopIssueExpiry(String value) {
        this.topIssueExpiry = value;
    }

    /**
     * Gets the value of the topIssueExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTopIssueExpiryDate() {
        return topIssueExpiryDate;
    }

    /**
     * Sets the value of the topIssueExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTopIssueExpiryDate(XMLGregorianCalendar value) {
        this.topIssueExpiryDate = value;
    }

    /**
     * Gets the value of the wrappedComponentFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrappedComponentFormat() {
        return wrappedComponentFormat;
    }

    /**
     * Sets the value of the wrappedComponentFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrappedComponentFormat(String value) {
        this.wrappedComponentFormat = value;
    }

    /**
     * Gets the value of the fileBytes property.
     * 
     */
    public long getFileBytes() {
        return fileBytes;
    }

    /**
     * Sets the value of the fileBytes property.
     * 
     */
    public void setFileBytes(long value) {
        this.fileBytes = value;
    }

    /**
     * Gets the value of the accountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCode(String value) {
        this.accountCode = value;
    }

    /**
     * Gets the value of the actionObjective property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionObjective() {
        return actionObjective;
    }

    /**
     * Sets the value of the actionObjective property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionObjective(String value) {
        this.actionObjective = value;
    }

    /**
     * Gets the value of the contentTopic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentTopic() {
        return contentTopic;
    }

    /**
     * Sets the value of the contentTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentTopic(String value) {
        this.contentTopic = value;
    }

    /**
     * Gets the value of the costPerIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostPerIssue() {
        return costPerIssue;
    }

    /**
     * Sets the value of the costPerIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostPerIssue(String value) {
        this.costPerIssue = value;
    }

    /**
     * Gets the value of the costPerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostPerUnit() {
        return costPerUnit;
    }

    /**
     * Sets the value of the costPerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostPerUnit(String value) {
        this.costPerUnit = value;
    }

    /**
     * Gets the value of the iaIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIaIdentifier() {
        return iaIdentifier;
    }

    /**
     * Sets the value of the iaIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIaIdentifier(String value) {
        this.iaIdentifier = value;
    }

    /**
     * Gets the value of the laborCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaborCost() {
        return laborCost;
    }

    /**
     * Sets the value of the laborCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaborCost(String value) {
        this.laborCost = value;
    }

    /**
     * Gets the value of the laborHoursPaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaborHoursPaid() {
        return laborHoursPaid;
    }

    /**
     * Sets the value of the laborHoursPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaborHoursPaid(String value) {
        this.laborHoursPaid = value;
    }

    /**
     * Gets the value of the laborMinutesPaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaborMinutesPaid() {
        return laborMinutesPaid;
    }

    /**
     * Sets the value of the laborMinutesPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaborMinutesPaid(String value) {
        this.laborMinutesPaid = value;
    }

    /**
     * Gets the value of the laborRatePerHour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaborRatePerHour() {
        return laborRatePerHour;
    }

    /**
     * Sets the value of the laborRatePerHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaborRatePerHour(String value) {
        this.laborRatePerHour = value;
    }

    /**
     * Gets the value of the mainComponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainComponent() {
        return mainComponent;
    }

    /**
     * Sets the value of the mainComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainComponent(String value) {
        this.mainComponent = value;
    }

    /**
     * Gets the value of the materialCostPerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialCostPerUnit() {
        return materialCostPerUnit;
    }

    /**
     * Sets the value of the materialCostPerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialCostPerUnit(String value) {
        this.materialCostPerUnit = value;
    }

    /**
     * Gets the value of the minorComponent1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorComponent1() {
        return minorComponent1;
    }

    /**
     * Sets the value of the minorComponent1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorComponent1(String value) {
        this.minorComponent1 = value;
    }

    /**
     * Gets the value of the minorComponent2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorComponent2() {
        return minorComponent2;
    }

    /**
     * Sets the value of the minorComponent2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorComponent2(String value) {
        this.minorComponent2 = value;
    }

    /**
     * Gets the value of the partsCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartsCost() {
        return partsCost;
    }

    /**
     * Sets the value of the partsCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartsCost(String value) {
        this.partsCost = value;
    }

    /**
     * Gets the value of the partsStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartsStrategy() {
        return partsStrategy;
    }

    /**
     * Sets the value of the partsStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartsStrategy(String value) {
        this.partsStrategy = value;
    }

    /**
     * Gets the value of the phpNavigation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhpNavigation() {
        return phpNavigation;
    }

    /**
     * Sets the value of the phpNavigation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhpNavigation(String value) {
        this.phpNavigation = value;
    }

    /**
     * Gets the value of the phpNavigationDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhpNavigationDetail() {
        return phpNavigationDetail;
    }

    /**
     * Sets the value of the phpNavigationDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhpNavigationDetail(String value) {
        this.phpNavigationDetail = value;
    }

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCategory(String value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the productDivision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDivision() {
        return productDivision;
    }

    /**
     * Sets the value of the productDivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDivision(String value) {
        this.productDivision = value;
    }

    /**
     * Gets the value of the productFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductFunction() {
        return productFunction;
    }

    /**
     * Sets the value of the productFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductFunction(String value) {
        this.productFunction = value;
    }

    /**
     * Gets the value of the serviceInventory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceInventory() {
        return serviceInventory;
    }

    /**
     * Sets the value of the serviceInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceInventory(String value) {
        this.serviceInventory = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the softwareTopic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareTopic() {
        return softwareTopic;
    }

    /**
     * Sets the value of the softwareTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareTopic(String value) {
        this.softwareTopic = value;
    }

    /**
     * Gets the value of the symptom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * Sets the value of the symptom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymptom(String value) {
        this.symptom = value;
    }

    /**
     * Gets the value of the travelCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTravelCost() {
        return travelCost;
    }

    /**
     * Sets the value of the travelCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTravelCost(String value) {
        this.travelCost = value;
    }

    /**
     * Gets the value of the usedPartsAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsedPartsAction() {
        return usedPartsAction;
    }

    /**
     * Sets the value of the usedPartsAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsedPartsAction(String value) {
        this.usedPartsAction = value;
    }

    /**
     * Gets the value of the userTask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTask() {
        return userTask;
    }

    /**
     * Sets the value of the userTask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTask(String value) {
        this.userTask = value;
    }

    /**
     * Gets the value of the actionExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActionExpiryDate() {
        return actionExpiryDate;
    }

    /**
     * Sets the value of the actionExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActionExpiryDate(XMLGregorianCalendar value) {
        this.actionExpiryDate = value;
    }

    /**
     * Gets the value of the actionStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActionStartDate() {
        return actionStartDate;
    }

    /**
     * Sets the value of the actionStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActionStartDate(XMLGregorianCalendar value) {
        this.actionStartDate = value;
    }

    /**
     * Gets the value of the effectivityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectivityDate() {
        return effectivityDate;
    }

    /**
     * Sets the value of the effectivityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectivityDate(XMLGregorianCalendar value) {
        this.effectivityDate = value;
    }

}
