package com.hp.cdsplus.processor;

public enum ProcessStatus {
	NEW_ITEM,
	DEL_EVENT_EVAL_STARTED,
	DEL_EVENT_EVAL_COMPLETE,
	SUB_EVAL_STARTED,
	SUB_EVAL_COMPLETE,
	SUB_PROCESSING_STARTED,
	SUB_PROCESSING_COMPLETE,
	DOCUMENT_PERSISTENCE_STARTED,
	DOCUMENT_PERSISTENCE_COMPLETE,
	LOAD_COMPLETE, 
	SERVICE_COMPLETE,
	SAVE_COMPLETE,
	HIERARCY_EVAL_STARTED,
	HIERARCY_EVAL_COMPLETE,
	METADATA_TRANS_STARTED,
	METADATA_TRANS_COMPLETE,
	CGS_EVALUATION_STARTED,
	CGS_EVALUATION_COMPLETE,
	CONTENT_TRANS_STARTED,
	CONTENT_TRANS_COMPLETE,
	MOVED_TO_LIVE,
	MOVED_TO_HISTORY,
	REMOVED_FROM_TEMP,
	FASTXML_CREATION_STARTED,
	FASTXML_CREATION_COMPLETE
}
