//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:11 AM IST 
//


package com.hp.concentra.bindings.output.schema.productsetup;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hp.concentra.bindings.output.schema.productsetup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProductLevel_QNAME = new QName("", "product_level");
    private final static QName _ColId_QNAME = new QName("", "col_id");
    private final static QName _CompanyInfo_QNAME = new QName("", "company_info");
    private final static QName _PalletPoundWeight_QNAME = new QName("", "pallet_pound_weight");
    private final static QName _AudienceExpiryDate_QNAME = new QName("", "audience_expiry_date");
    private final static QName _LanguageCode_QNAME = new QName("", "language_code");
    private final static QName _Action_QNAME = new QName("", "action");
    private final static QName _UpcNumber_QNAME = new QName("", "upc_number");
    private final static QName _ProductTariffCode_QNAME = new QName("", "product_tariff_code");
    private final static QName _MasterObjectName_QNAME = new QName("", "master_object_name");
    private final static QName _ExtraPropertyValue_QNAME = new QName("", "extra_property_value");
    private final static QName _PalletNumber_QNAME = new QName("", "pallet_number");
    private final static QName _ProductWarrantySummary_QNAME = new QName("", "product_warranty_summary");
    private final static QName _CreationDate_QNAME = new QName("", "creation_date");
    private final static QName _Priority_QNAME = new QName("", "priority");
    private final static QName _PackagedInchDepth_QNAME = new QName("", "packaged_inch_depth");
    private final static QName _ContentVersion_QNAME = new QName("", "content_version");
    private final static QName _ReviewDate_QNAME = new QName("", "review_date");
    private final static QName _AudienceName_QNAME = new QName("", "audience_name");
    private final static QName _PalletInchDepth_QNAME = new QName("", "pallet_inch_depth");
    private final static QName _ProductDiscountQuantity_QNAME = new QName("", "product_discount_quantity");
    private final static QName _PackagedInchHeight_QNAME = new QName("", "packaged_inch_height");
    private final static QName _PackagedPoundWeight_QNAME = new QName("", "packaged_pound_weight");
    private final static QName _ProductMarket_QNAME = new QName("", "product_market");
    private final static QName _UnpackagedInchHeight_QNAME = new QName("", "unpackaged_inch_height");
    private final static QName _OriginalDocid_QNAME = new QName("", "original_docid");
    private final static QName _ProductCompatibility_QNAME = new QName("", "product_compatibility");
    private final static QName _DisclosureLevel_QNAME = new QName("", "disclosure_level");
    private final static QName _ProductNetPrice1_QNAME = new QName("", "product_net_price_1");
    private final static QName _ProductNetPrice2_QNAME = new QName("", "product_net_price_2");
    private final static QName _ProductShelfLife_QNAME = new QName("", "product_shelf_life");
    private final static QName _PlannedPublicDate_QNAME = new QName("", "planned_public_date");
    private final static QName _PalletInchWidth_QNAME = new QName("", "pallet_inch_width");
    private final static QName _MasterCartonInchHeight_QNAME = new QName("", "master_carton_inch_height");
    private final static QName _ObjectName_QNAME = new QName("", "object_name");
    private final static QName _PackagedInchWidth_QNAME = new QName("", "packaged_inch_width");
    private final static QName _Currency_QNAME = new QName("", "currency");
    private final static QName _PalletLayerCount_QNAME = new QName("", "pallet_layer_count");
    private final static QName _DocumentType_QNAME = new QName("", "document_type");
    private final static QName _PropertyUpdateDate_QNAME = new QName("", "property_update_date");
    private final static QName _InnerPackNumber_QNAME = new QName("", "inner_pack_number");
    private final static QName _ColorPageYieldCount_QNAME = new QName("", "color_page_yield_count");
    private final static QName _TechnologyType_QNAME = new QName("", "technology_type");
    private final static QName _UnpackagedInchDepth_QNAME = new QName("", "unpackaged_inch_depth");
    private final static QName _UnpackagedInchWidth_QNAME = new QName("", "unpackaged_inch_width");
    private final static QName _PrEmbargoDate_QNAME = new QName("", "pr_embargo_date");
    private final static QName _ProductMapFlag_QNAME = new QName("", "product_map_flag");
    private final static QName _ProductListPrice_QNAME = new QName("", "product_list_price");
    private final static QName _PalletDiscount_QNAME = new QName("", "pallet_discount");
    private final static QName _Component_QNAME = new QName("", "component");
    private final static QName _MasterCartonNetPrice_QNAME = new QName("", "master_carton_net_price");
    private final static QName _ProductMapPrice_QNAME = new QName("", "product_map_price");
    private final static QName _UnpackagedPoundWeight_QNAME = new QName("", "unpackaged_pound_weight");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _ReplacedProduct_QNAME = new QName("", "replaced_product");
    private final static QName _KeySellingPoints_QNAME = new QName("", "key_selling_points");
    private final static QName _ValidFlag_QNAME = new QName("", "valid_flag");
    private final static QName _AudienceReleaseDate_QNAME = new QName("", "audience_release_date");
    private final static QName _DocumentClass_QNAME = new QName("", "document_class");
    private final static QName _OriginalFilename_QNAME = new QName("", "original_filename");
    private final static QName _MasterCartonPoundWeight_QNAME = new QName("", "master_carton_pound_weight");
    private final static QName _PalletInchHeight_QNAME = new QName("", "pallet_inch_height");
    private final static QName _PalletNetPrice_QNAME = new QName("", "pallet_net_price");
    private final static QName _BundleDimensionsText_QNAME = new QName("", "bundle_dimensions_text");
    private final static QName _MiscellaneousComment_QNAME = new QName("", "miscellaneous_comment");
    private final static QName _ContentHistory_QNAME = new QName("", "content_history");
    private final static QName _Author_QNAME = new QName("", "author");
    private final static QName _PalletListPrice_QNAME = new QName("", "pallet_list_price");
    private final static QName _InformationSource_QNAME = new QName("", "information_source");
    private final static QName _OriginalSystem_QNAME = new QName("", "original_system");
    private final static QName _ContentUpdateDate_QNAME = new QName("", "content_update_date");
    private final static QName _CmgAcronym_QNAME = new QName("", "cmg_acronym");
    private final static QName _MasterCartonNumber_QNAME = new QName("", "master_carton_number");
    private final static QName _Region_QNAME = new QName("", "region");
    private final static QName _RObjectId_QNAME = new QName("", "r_object_id");
    private final static QName _ProductMinOrderQuantity_QNAME = new QName("", "product_min_order_quantity");
    private final static QName _CollectionValidFlag_QNAME = new QName("", "collection_valid_flag");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _CplDate_QNAME = new QName("", "cpl_date");
    private final static QName _ProductOption_QNAME = new QName("", "product_option");
    private final static QName _ProductDiscount1_QNAME = new QName("", "product_discount_1");
    private final static QName _ContentType_QNAME = new QName("", "content_type");
    private final static QName _AdEmbargoDate_QNAME = new QName("", "ad_embargo_date");
    private final static QName _PalletCartonsPerLayer_QNAME = new QName("", "pallet_cartons_per_layer");
    private final static QName _ProductDiscount2_QNAME = new QName("", "product_discount_2");
    private final static QName _MonochromePageYieldCount_QNAME = new QName("", "monochrome_page_yield_count");
    private final static QName _VersionLabel_QNAME = new QName("", "version_label");
    private final static QName _MasterCartonInchDepth_QNAME = new QName("", "master_carton_inch_depth");
    private final static QName _PalletProductsPerLayer_QNAME = new QName("", "pallet_products_per_layer");
    private final static QName _SearchKeyword_QNAME = new QName("", "search_keyword");
    private final static QName _Orientation_QNAME = new QName("", "orientation");
    private final static QName _MasterCartonDiscount_QNAME = new QName("", "master_carton_discount");
    private final static QName _MarketingTeam_QNAME = new QName("", "marketing_team");
    private final static QName _MasterCartonInchWidth_QNAME = new QName("", "master_carton_inch_width");
    private final static QName _PackageContent_QNAME = new QName("", "package_content");
    private final static QName _MasterCartonListPrice_QNAME = new QName("", "master_carton_list_price");
    private final static QName _CmgFeedbackAddress_QNAME = new QName("", "cmg_feedback_address");
    private final static QName _OrderDate_QNAME = new QName("", "order_date");
    private final static QName _PalletProductCount_QNAME = new QName("", "pallet_product_count");
    private final static QName _MasterCartonProductCount_QNAME = new QName("", "master_carton_product_count");
    private final static QName _LanguageLabel_QNAME = new QName("", "language_label");
    private final static QName _ExtraPropertyName_QNAME = new QName("", "extra_property_name");
    private final static QName _ProductEstStreetPrice_QNAME = new QName("", "product_est_street_price");
    private final static QName _ConfidentialComment_QNAME = new QName("", "confidential_comment");
    private final static QName _HasValidProducts_QNAME = new QName("", "has_valid_products");
    private final static QName _ShowAsNewDuration_QNAME = new QName("", "show_as_new_duration");
    private final static QName _Account_QNAME = new QName("", "account");
    private final static QName _ShipDate_QNAME = new QName("", "ship_date");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hp.concentra.bindings.output.schema.productsetup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductMarkets }
     * 
     */
    public ProductMarkets createProductMarkets() {
        return new ProductMarkets();
    }

    /**
     * Create an instance of {@link ProductLevels }
     * 
     */
    public ProductLevels createProductLevels() {
        return new ProductLevels();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link Associations }
     * 
     */
    public Associations createAssociations() {
        return new Associations();
    }

    /**
     * Create an instance of {@link Projectref }
     * 
     */
    public Projectref createProjectref() {
        return new Projectref();
    }

    /**
     * Create an instance of {@link OriginCountries }
     * 
     */
    public OriginCountries createOriginCountries() {
        return new OriginCountries();
    }

    /**
     * Create an instance of {@link ProductBigSeries }
     * 
     */
    public ProductBigSeries createProductBigSeries() {
        return new ProductBigSeries();
    }

    /**
     * Create an instance of {@link SupportNameOids }
     * 
     */
    public SupportNameOids createSupportNameOids() {
        return new SupportNameOids();
    }

    /**
     * Create an instance of {@link ProductTypes }
     * 
     */
    public ProductTypes createProductTypes() {
        return new ProductTypes();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ProductNames }
     * 
     */
    public ProductNames createProductNames() {
        return new ProductNames();
    }

    /**
     * Create an instance of {@link FullTitle }
     * 
     */
    public FullTitle createFullTitle() {
        return new FullTitle();
    }

    /**
     * Create an instance of {@link ProductNumbers }
     * 
     */
    public ProductNumbers createProductNumbers() {
        return new ProductNumbers();
    }

    /**
     * Create an instance of {@link DocumentTypeDetails }
     * 
     */
    public DocumentTypeDetails createDocumentTypeDetails() {
        return new DocumentTypeDetails();
    }

    /**
     * Create an instance of {@link Regions }
     * 
     */
    public Regions createRegions() {
        return new Regions();
    }

    /**
     * Create an instance of {@link Audience }
     * 
     */
    public Audience createAudience() {
        return new Audience();
    }

    /**
     * Create an instance of {@link ProductSeries }
     * 
     */
    public ProductSeries createProductSeries() {
        return new ProductSeries();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link ExtraProperties }
     * 
     */
    public ExtraProperties createExtraProperties() {
        return new ExtraProperties();
    }

    /**
     * Create an instance of {@link Audiences }
     * 
     */
    public Audiences createAudiences() {
        return new Audiences();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link MarketingTeams }
     * 
     */
    public MarketingTeams createMarketingTeams() {
        return new MarketingTeams();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link ProductSupportCategories }
     * 
     */
    public ProductSupportCategories createProductSupportCategories() {
        return new ProductSupportCategories();
    }

    /**
     * Create an instance of {@link ProductLines }
     * 
     */
    public ProductLines createProductLines() {
        return new ProductLines();
    }

    /**
     * Create an instance of {@link ProductMarketingSubcategories }
     * 
     */
    public ProductMarketingSubcategories createProductMarketingSubcategories() {
        return new ProductMarketingSubcategories();
    }

    /**
     * Create an instance of {@link FileName }
     * 
     */
    public FileName createFileName() {
        return new FileName();
    }

    /**
     * Create an instance of {@link ProductNumberNames }
     * 
     */
    public ProductNumberNames createProductNumberNames() {
        return new ProductNumberNames();
    }

    /**
     * Create an instance of {@link Content }
     * 
     */
    public Content createContent() {
        return new Content();
    }

    /**
     * Create an instance of {@link ProductSupportSubcategories }
     * 
     */
    public ProductSupportSubcategories createProductSupportSubcategories() {
        return new ProductSupportSubcategories();
    }

    /**
     * Create an instance of {@link ProductMarketingCategories }
     * 
     */
    public ProductMarketingCategories createProductMarketingCategories() {
        return new ProductMarketingCategories();
    }

    /**
     * Create an instance of {@link LanguageCodes }
     * 
     */
    public LanguageCodes createLanguageCodes() {
        return new LanguageCodes();
    }

    /**
     * Create an instance of {@link Countries }
     * 
     */
    public Countries createCountries() {
        return new Countries();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link ExtraPropertyValues }
     * 
     */
    public ExtraPropertyValues createExtraPropertyValues() {
        return new ExtraPropertyValues();
    }

    /**
     * Create an instance of {@link ExtraProperty }
     * 
     */
    public ExtraProperty createExtraProperty() {
        return new ExtraProperty();
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link SearchKeywords }
     * 
     */
    public SearchKeywords createSearchKeywords() {
        return new SearchKeywords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_level")
    public JAXBElement<String> createProductLevel(String value) {
        return new JAXBElement<String>(_ProductLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "col_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createColId(String value) {
        return new JAXBElement<String>(_ColId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "company_info")
    public JAXBElement<String> createCompanyInfo(String value) {
        return new JAXBElement<String>(_CompanyInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_pound_weight")
    public JAXBElement<String> createPalletPoundWeight(String value) {
        return new JAXBElement<String>(_PalletPoundWeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "audience_expiry_date")
    public JAXBElement<XMLGregorianCalendar> createAudienceExpiryDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AudienceExpiryDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language_code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguageCode(String value) {
        return new JAXBElement<String>(_LanguageCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "upc_number")
    public JAXBElement<String> createUpcNumber(String value) {
        return new JAXBElement<String>(_UpcNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_tariff_code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductTariffCode(String value) {
        return new JAXBElement<String>(_ProductTariffCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_object_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMasterObjectName(String value) {
        return new JAXBElement<String>(_MasterObjectName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extra_property_value")
    public JAXBElement<String> createExtraPropertyValue(String value) {
        return new JAXBElement<String>(_ExtraPropertyValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_number")
    public JAXBElement<String> createPalletNumber(String value) {
        return new JAXBElement<String>(_PalletNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_warranty_summary")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductWarrantySummary(String value) {
        return new JAXBElement<String>(_ProductWarrantySummary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creation_date")
    public JAXBElement<XMLGregorianCalendar> createCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority")
    public JAXBElement<BigInteger> createPriority(BigInteger value) {
        return new JAXBElement<BigInteger>(_Priority_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "packaged_inch_depth")
    public JAXBElement<String> createPackagedInchDepth(String value) {
        return new JAXBElement<String>(_PackagedInchDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content_version")
    public JAXBElement<String> createContentVersion(String value) {
        return new JAXBElement<String>(_ContentVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "review_date")
    public JAXBElement<XMLGregorianCalendar> createReviewDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ReviewDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "audience_name")
    public JAXBElement<String> createAudienceName(String value) {
        return new JAXBElement<String>(_AudienceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_inch_depth")
    public JAXBElement<String> createPalletInchDepth(String value) {
        return new JAXBElement<String>(_PalletInchDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_discount_quantity")
    public JAXBElement<String> createProductDiscountQuantity(String value) {
        return new JAXBElement<String>(_ProductDiscountQuantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "packaged_inch_height")
    public JAXBElement<String> createPackagedInchHeight(String value) {
        return new JAXBElement<String>(_PackagedInchHeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "packaged_pound_weight")
    public JAXBElement<String> createPackagedPoundWeight(String value) {
        return new JAXBElement<String>(_PackagedPoundWeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_market")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductMarket(String value) {
        return new JAXBElement<String>(_ProductMarket_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unpackaged_inch_height")
    public JAXBElement<String> createUnpackagedInchHeight(String value) {
        return new JAXBElement<String>(_UnpackagedInchHeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original_docid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalDocid(String value) {
        return new JAXBElement<String>(_OriginalDocid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_compatibility")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductCompatibility(String value) {
        return new JAXBElement<String>(_ProductCompatibility_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "disclosure_level")
    public JAXBElement<String> createDisclosureLevel(String value) {
        return new JAXBElement<String>(_DisclosureLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_net_price_1")
    public JAXBElement<String> createProductNetPrice1(String value) {
        return new JAXBElement<String>(_ProductNetPrice1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_net_price_2")
    public JAXBElement<String> createProductNetPrice2(String value) {
        return new JAXBElement<String>(_ProductNetPrice2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_shelf_life")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductShelfLife(String value) {
        return new JAXBElement<String>(_ProductShelfLife_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "planned_public_date")
    public JAXBElement<XMLGregorianCalendar> createPlannedPublicDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlannedPublicDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_inch_width")
    public JAXBElement<String> createPalletInchWidth(String value) {
        return new JAXBElement<String>(_PalletInchWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_inch_height")
    public JAXBElement<String> createMasterCartonInchHeight(String value) {
        return new JAXBElement<String>(_MasterCartonInchHeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "object_name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createObjectName(String value) {
        return new JAXBElement<String>(_ObjectName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "packaged_inch_width")
    public JAXBElement<String> createPackagedInchWidth(String value) {
        return new JAXBElement<String>(_PackagedInchWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "currency")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_layer_count")
    public JAXBElement<String> createPalletLayerCount(String value) {
        return new JAXBElement<String>(_PalletLayerCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "document_type")
    public JAXBElement<String> createDocumentType(String value) {
        return new JAXBElement<String>(_DocumentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property_update_date")
    public JAXBElement<XMLGregorianCalendar> createPropertyUpdateDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PropertyUpdateDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inner_pack_number")
    public JAXBElement<BigInteger> createInnerPackNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_InnerPackNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color_page_yield_count")
    public JAXBElement<String> createColorPageYieldCount(String value) {
        return new JAXBElement<String>(_ColorPageYieldCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "technology_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTechnologyType(String value) {
        return new JAXBElement<String>(_TechnologyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unpackaged_inch_depth")
    public JAXBElement<String> createUnpackagedInchDepth(String value) {
        return new JAXBElement<String>(_UnpackagedInchDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unpackaged_inch_width")
    public JAXBElement<String> createUnpackagedInchWidth(String value) {
        return new JAXBElement<String>(_UnpackagedInchWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pr_embargo_date")
    public JAXBElement<XMLGregorianCalendar> createPrEmbargoDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PrEmbargoDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_map_flag")
    public JAXBElement<Boolean> createProductMapFlag(Boolean value) {
        return new JAXBElement<Boolean>(_ProductMapFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_list_price")
    public JAXBElement<String> createProductListPrice(String value) {
        return new JAXBElement<String>(_ProductListPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_discount")
    public JAXBElement<String> createPalletDiscount(String value) {
        return new JAXBElement<String>(_PalletDiscount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "component")
    public JAXBElement<String> createComponent(String value) {
        return new JAXBElement<String>(_Component_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_net_price")
    public JAXBElement<String> createMasterCartonNetPrice(String value) {
        return new JAXBElement<String>(_MasterCartonNetPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_map_price")
    public JAXBElement<String> createProductMapPrice(String value) {
        return new JAXBElement<String>(_ProductMapPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unpackaged_pound_weight")
    public JAXBElement<String> createUnpackagedPoundWeight(String value) {
        return new JAXBElement<String>(_UnpackagedPoundWeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "replaced_product")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReplacedProduct(String value) {
        return new JAXBElement<String>(_ReplacedProduct_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "key_selling_points")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createKeySellingPoints(String value) {
        return new JAXBElement<String>(_KeySellingPoints_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valid_flag")
    public JAXBElement<Boolean> createValidFlag(Boolean value) {
        return new JAXBElement<Boolean>(_ValidFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "audience_release_date")
    public JAXBElement<XMLGregorianCalendar> createAudienceReleaseDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AudienceReleaseDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "document_class")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDocumentClass(String value) {
        return new JAXBElement<String>(_DocumentClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original_filename")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOriginalFilename(String value) {
        return new JAXBElement<String>(_OriginalFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_pound_weight")
    public JAXBElement<String> createMasterCartonPoundWeight(String value) {
        return new JAXBElement<String>(_MasterCartonPoundWeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_inch_height")
    public JAXBElement<String> createPalletInchHeight(String value) {
        return new JAXBElement<String>(_PalletInchHeight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_net_price")
    public JAXBElement<String> createPalletNetPrice(String value) {
        return new JAXBElement<String>(_PalletNetPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bundle_dimensions_text")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBundleDimensionsText(String value) {
        return new JAXBElement<String>(_BundleDimensionsText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "miscellaneous_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMiscellaneousComment(String value) {
        return new JAXBElement<String>(_MiscellaneousComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content_history")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createContentHistory(String value) {
        return new JAXBElement<String>(_ContentHistory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "author")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_list_price")
    public JAXBElement<String> createPalletListPrice(String value) {
        return new JAXBElement<String>(_PalletListPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "information_source")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInformationSource(String value) {
        return new JAXBElement<String>(_InformationSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original_system")
    public JAXBElement<String> createOriginalSystem(String value) {
        return new JAXBElement<String>(_OriginalSystem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content_update_date")
    public JAXBElement<XMLGregorianCalendar> createContentUpdateDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ContentUpdateDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cmg_acronym")
    public JAXBElement<String> createCmgAcronym(String value) {
        return new JAXBElement<String>(_CmgAcronym_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_number")
    public JAXBElement<BigInteger> createMasterCartonNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_MasterCartonNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "r_object_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRObjectId(String value) {
        return new JAXBElement<String>(_RObjectId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_min_order_quantity")
    public JAXBElement<String> createProductMinOrderQuantity(String value) {
        return new JAXBElement<String>(_ProductMinOrderQuantity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collection_valid_flag")
    public JAXBElement<Boolean> createCollectionValidFlag(Boolean value) {
        return new JAXBElement<Boolean>(_CollectionValidFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cpl_date")
    public JAXBElement<XMLGregorianCalendar> createCplDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CplDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_option")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createProductOption(String value) {
        return new JAXBElement<String>(_ProductOption_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_discount_1")
    public JAXBElement<String> createProductDiscount1(String value) {
        return new JAXBElement<String>(_ProductDiscount1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content_type")
    public JAXBElement<String> createContentType(String value) {
        return new JAXBElement<String>(_ContentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ad_embargo_date")
    public JAXBElement<XMLGregorianCalendar> createAdEmbargoDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AdEmbargoDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_cartons_per_layer")
    public JAXBElement<String> createPalletCartonsPerLayer(String value) {
        return new JAXBElement<String>(_PalletCartonsPerLayer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_discount_2")
    public JAXBElement<String> createProductDiscount2(String value) {
        return new JAXBElement<String>(_ProductDiscount2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "monochrome_page_yield_count")
    public JAXBElement<String> createMonochromePageYieldCount(String value) {
        return new JAXBElement<String>(_MonochromePageYieldCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version_label")
    public JAXBElement<String> createVersionLabel(String value) {
        return new JAXBElement<String>(_VersionLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_inch_depth")
    public JAXBElement<String> createMasterCartonInchDepth(String value) {
        return new JAXBElement<String>(_MasterCartonInchDepth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_products_per_layer")
    public JAXBElement<String> createPalletProductsPerLayer(String value) {
        return new JAXBElement<String>(_PalletProductsPerLayer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "search_keyword")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSearchKeyword(String value) {
        return new JAXBElement<String>(_SearchKeyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orientation")
    public JAXBElement<String> createOrientation(String value) {
        return new JAXBElement<String>(_Orientation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_discount")
    public JAXBElement<String> createMasterCartonDiscount(String value) {
        return new JAXBElement<String>(_MasterCartonDiscount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "marketing_team")
    public JAXBElement<String> createMarketingTeam(String value) {
        return new JAXBElement<String>(_MarketingTeam_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_inch_width")
    public JAXBElement<String> createMasterCartonInchWidth(String value) {
        return new JAXBElement<String>(_MasterCartonInchWidth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "package_content")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPackageContent(String value) {
        return new JAXBElement<String>(_PackageContent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_list_price")
    public JAXBElement<BigInteger> createMasterCartonListPrice(BigInteger value) {
        return new JAXBElement<BigInteger>(_MasterCartonListPrice_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cmg_feedback_address")
    public JAXBElement<String> createCmgFeedbackAddress(String value) {
        return new JAXBElement<String>(_CmgFeedbackAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order_date")
    public JAXBElement<XMLGregorianCalendar> createOrderDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pallet_product_count")
    public JAXBElement<String> createPalletProductCount(String value) {
        return new JAXBElement<String>(_PalletProductCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "master_carton_product_count")
    public JAXBElement<String> createMasterCartonProductCount(String value) {
        return new JAXBElement<String>(_MasterCartonProductCount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language_label")
    public JAXBElement<String> createLanguageLabel(String value) {
        return new JAXBElement<String>(_LanguageLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extra_property_name")
    public JAXBElement<String> createExtraPropertyName(String value) {
        return new JAXBElement<String>(_ExtraPropertyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "product_est_street_price")
    public JAXBElement<String> createProductEstStreetPrice(String value) {
        return new JAXBElement<String>(_ProductEstStreetPrice_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "confidential_comment")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createConfidentialComment(String value) {
        return new JAXBElement<String>(_ConfidentialComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "has_valid_products")
    public JAXBElement<Boolean> createHasValidProducts(Boolean value) {
        return new JAXBElement<Boolean>(_HasValidProducts_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "show_as_new_duration")
    public JAXBElement<String> createShowAsNewDuration(String value) {
        return new JAXBElement<String>(_ShowAsNewDuration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "account")
    public JAXBElement<String> createAccount(String value) {
        return new JAXBElement<String>(_Account_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ship_date")
    public JAXBElement<XMLGregorianCalendar> createShipDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ShipDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
