//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:00 AM IST 
//


package com.hp.soar.bindings.output.schema.soar;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}product" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_types" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_support_subcategories" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_series" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_names" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_numbers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_number_names" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_lines" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_support_categories" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_big_series" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_marketing_categories" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}product_marketing_subcategories" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}support_name_oids" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "product",
    "productTypes",
    "productSupportSubcategories",
    "productSeries",
    "productNames",
    "productNumbers",
    "productNumberNames",
    "productLines",
    "productSupportCategories",
    "productBigSeries",
    "productMarketingCategories",
    "productMarketingSubcategories",
    "supportNameOids"
})
@XmlRootElement(name = "products-supported")
public class ProductsSupported {

    @XmlElement(required = true)
    protected List<Product> product;
    @XmlElement(name = "product_types", required = true)
    protected List<ProductTypes> productTypes;
    @XmlElement(name = "product_support_subcategories", required = true)
    protected List<ProductSupportSubcategories> productSupportSubcategories;
    @XmlElement(name = "product_series", required = true)
    protected List<ProductSeries> productSeries;
    @XmlElement(name = "product_names", required = true)
    protected List<ProductNames> productNames;
    @XmlElement(name = "product_numbers", required = true)
    protected List<ProductNumbers> productNumbers;
    @XmlElement(name = "product_number_names", required = true)
    protected List<ProductNumberNames> productNumberNames;
    @XmlElement(name = "product_lines", required = true)
    protected List<ProductLines> productLines;
    @XmlElement(name = "product_support_categories", required = true)
    protected List<ProductSupportCategories> productSupportCategories;
    @XmlElement(name = "product_big_series", required = true)
    protected List<ProductBigSeries> productBigSeries;
    @XmlElement(name = "product_marketing_categories", required = true)
    protected List<ProductMarketingCategories> productMarketingCategories;
    @XmlElement(name = "product_marketing_subcategories", required = true)
    protected List<ProductMarketingSubcategories> productMarketingSubcategories;
    @XmlElement(name = "support_name_oids", required = true)
    protected List<SupportNameOids> supportNameOids;

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Product }
     * 
     * 
     */
    public List<Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Product>();
        }
        return this.product;
    }

    /**
     * Gets the value of the productTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductTypes }
     * 
     * 
     */
    public List<ProductTypes> getProductTypes() {
        if (productTypes == null) {
            productTypes = new ArrayList<ProductTypes>();
        }
        return this.productTypes;
    }

    /**
     * Gets the value of the productSupportSubcategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productSupportSubcategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductSupportSubcategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductSupportSubcategories }
     * 
     * 
     */
    public List<ProductSupportSubcategories> getProductSupportSubcategories() {
        if (productSupportSubcategories == null) {
            productSupportSubcategories = new ArrayList<ProductSupportSubcategories>();
        }
        return this.productSupportSubcategories;
    }

    /**
     * Gets the value of the productSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductSeries }
     * 
     * 
     */
    public List<ProductSeries> getProductSeries() {
        if (productSeries == null) {
            productSeries = new ArrayList<ProductSeries>();
        }
        return this.productSeries;
    }

    /**
     * Gets the value of the productNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductNames }
     * 
     * 
     */
    public List<ProductNames> getProductNames() {
        if (productNames == null) {
            productNames = new ArrayList<ProductNames>();
        }
        return this.productNames;
    }

    /**
     * Gets the value of the productNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductNumbers }
     * 
     * 
     */
    public List<ProductNumbers> getProductNumbers() {
        if (productNumbers == null) {
            productNumbers = new ArrayList<ProductNumbers>();
        }
        return this.productNumbers;
    }

    /**
     * Gets the value of the productNumberNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productNumberNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductNumberNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductNumberNames }
     * 
     * 
     */
    public List<ProductNumberNames> getProductNumberNames() {
        if (productNumberNames == null) {
            productNumberNames = new ArrayList<ProductNumberNames>();
        }
        return this.productNumberNames;
    }

    /**
     * Gets the value of the productLines property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productLines property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductLines().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductLines }
     * 
     * 
     */
    public List<ProductLines> getProductLines() {
        if (productLines == null) {
            productLines = new ArrayList<ProductLines>();
        }
        return this.productLines;
    }

    /**
     * Gets the value of the productSupportCategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productSupportCategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductSupportCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductSupportCategories }
     * 
     * 
     */
    public List<ProductSupportCategories> getProductSupportCategories() {
        if (productSupportCategories == null) {
            productSupportCategories = new ArrayList<ProductSupportCategories>();
        }
        return this.productSupportCategories;
    }

    /**
     * Gets the value of the productBigSeries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productBigSeries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductBigSeries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductBigSeries }
     * 
     * 
     */
    public List<ProductBigSeries> getProductBigSeries() {
        if (productBigSeries == null) {
            productBigSeries = new ArrayList<ProductBigSeries>();
        }
        return this.productBigSeries;
    }

    /**
     * Gets the value of the productMarketingCategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productMarketingCategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductMarketingCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductMarketingCategories }
     * 
     * 
     */
    public List<ProductMarketingCategories> getProductMarketingCategories() {
        if (productMarketingCategories == null) {
            productMarketingCategories = new ArrayList<ProductMarketingCategories>();
        }
        return this.productMarketingCategories;
    }

    /**
     * Gets the value of the productMarketingSubcategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productMarketingSubcategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductMarketingSubcategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductMarketingSubcategories }
     * 
     * 
     */
    public List<ProductMarketingSubcategories> getProductMarketingSubcategories() {
        if (productMarketingSubcategories == null) {
            productMarketingSubcategories = new ArrayList<ProductMarketingSubcategories>();
        }
        return this.productMarketingSubcategories;
    }

    /**
     * Gets the value of the supportNameOids property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportNameOids property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportNameOids().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportNameOids }
     * 
     * 
     */
    public List<SupportNameOids> getSupportNameOids() {
        if (supportNameOids == null) {
            supportNameOids = new ArrayList<SupportNameOids>();
        }
        return this.supportNameOids;
    }

}
