//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:14 AM IST 
//


package com.hp.cdsplus.bindings.output.schema.productmaster;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}heirarchy_level"/>
 *         &lt;element ref="{}node_type"/>
 *         &lt;element ref="{}Rich_text" minOccurs="0"/>
 *         &lt;element ref="{}company_designation" minOccurs="0"/>
 *         &lt;element ref="{}lifecycle_status_code"/>
 *         &lt;element ref="{}material_type_code"/>
 *         &lt;element ref="{}platform_id"/>
 *         &lt;element ref="{}pn_product_line"/>
 *         &lt;element ref="{}product_classification"/>
 *         &lt;element ref="{}product_number"/>
 *         &lt;element ref="{}product_number_description"/>
 *         &lt;element ref="{}serial_flag"/>
 *         &lt;element ref="{}tangible_flag"/>
 *         &lt;element ref="{}children"/>
 *         &lt;element ref="{}parents"/>
 *         &lt;element ref="{http://www.hp.com/cdsplus}view"/>
 *         &lt;element ref="{}Unspsc_code"/>
 *         &lt;element ref="{}name" maxOccurs="unbounded"/>
 *         &lt;element ref="{}snf"/>
 *         &lt;element ref="{}sni"/>
 *         &lt;element ref="{}Rich_text"/>
 *         &lt;element ref="{}long_name" maxOccurs="unbounded"/>
 *         &lt;element ref="{}product_line"/>
 *         &lt;element ref="{}cc_bsc_release_date"/>
 *         &lt;element ref="{}hierarchy_status"/>
 *         &lt;element ref="{}product_line_description"/>
 *         &lt;element ref="{}support_name_oid"/>
 *         &lt;element ref="{}support_publishing_flag"/>
 *         &lt;element ref="{}web_destination"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "node")
public class Node {

    @XmlElementRefs({
        @XmlElementRef(name = "product_line", type = JAXBElement.class),
        @XmlElementRef(name = "children", type = Children.class),
        @XmlElementRef(name = "Rich_text", type = JAXBElement.class),
        @XmlElementRef(name = "support_publishing_flag", type = JAXBElement.class),
        @XmlElementRef(name = "tangible_flag", type = JAXBElement.class),
        @XmlElementRef(name = "snf", type = JAXBElement.class),
        @XmlElementRef(name = "heirarchy_level", type = JAXBElement.class),
        @XmlElementRef(name = "support_name_oid", type = JAXBElement.class),
        @XmlElementRef(name = "view", namespace = "http://www.hp.com/cdsplus", type = View.class),
        @XmlElementRef(name = "name", type = Name.class),
        @XmlElementRef(name = "product_classification", type = JAXBElement.class),
        @XmlElementRef(name = "pn_product_line", type = JAXBElement.class),
        @XmlElementRef(name = "Unspsc_code", type = JAXBElement.class),
        @XmlElementRef(name = "material_type_code", type = JAXBElement.class),
        @XmlElementRef(name = "node_type", type = JAXBElement.class),
        @XmlElementRef(name = "platform_id", type = JAXBElement.class),
        @XmlElementRef(name = "web_destination", type = JAXBElement.class),
        @XmlElementRef(name = "hierarchy_status", type = JAXBElement.class),
        @XmlElementRef(name = "company_designation", type = JAXBElement.class),
        @XmlElementRef(name = "cc_bsc_release_date", type = JAXBElement.class),
        @XmlElementRef(name = "product_number_description", type = JAXBElement.class),
        @XmlElementRef(name = "product_number", type = JAXBElement.class),
        @XmlElementRef(name = "product_line_description", type = JAXBElement.class),
        @XmlElementRef(name = "lifecycle_status_code", type = JAXBElement.class),
        @XmlElementRef(name = "sni", type = JAXBElement.class),
        @XmlElementRef(name = "serial_flag", type = JAXBElement.class),
        @XmlElementRef(name = "parents", type = Parents.class),
        @XmlElementRef(name = "long_name", type = LongName.class)
    })
    protected List<Object> content;
    @XmlAttribute
    protected String id;
    @XmlAttribute(required = true)
    protected BigInteger oid;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String base;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "RichText" is used by two different parts of a schema. See: 
     * line 48 of file:/C:/Users/RADHA/PROJECTS/CDSPLUS/cdsp-bindings/schema/output/cdsplus/productmaster.xsd
     * line 30 of file:/C:/Users/RADHA/PROJECTS/CDSPLUS/cdsp-bindings/schema/output/cdsplus/productmaster.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Children }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link View }
     * {@link Name }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Parents }
     * {@link LongName }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOid() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOid(BigInteger value) {
        this.oid = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
