//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:15 AM IST 
//


package com.hp.cdsplus.bindings.output.schema.stylesheetsubscription;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}subscriptionName"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}output"/>
 *         &lt;element ref="{}imported-styles"/>
 *         &lt;element ref="{}proj_path_seperator"/>
 *         &lt;element ref="{}proj_path_parts"/>
 *         &lt;element ref="{}proj_namespace_types"/>
 *         &lt;element ref="{}proj_is_smartfolder"/>
 *         &lt;element ref="{}embedded_criteria_filter"/>
 *         &lt;element ref="{}filter"/>
 *         &lt;element ref="{}delivery"/>
 *         &lt;element ref="{}smartfolder"/>
 *         &lt;element ref="{}hierarchyExpansions"/>
 *         &lt;element ref="{}stylesheet_name"/>
 *         &lt;element ref="{}FastRepeatingValueSeparator"/>
 *         &lt;element ref="{}currentProjNamespace"/>
 *         &lt;element ref="{}exclude_software-items_by_disclosure-level"/>
 *         &lt;element ref="{}disclosure-level_whitelist"/>
 *         &lt;element ref="{}TaxonomyKeyValueSeperator"/>
 *         &lt;element ref="{}TaxonomyRepeatingValueSeparator"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subscriptionName",
    "type",
    "output",
    "importedStyles",
    "projPathSeperator",
    "projPathParts",
    "projNamespaceTypes",
    "projIsSmartfolder",
    "embeddedCriteriaFilter",
    "filter",
    "delivery",
    "smartfolder",
    "hierarchyExpansions",
    "stylesheetName",
    "fastRepeatingValueSeparator",
    "currentProjNamespace",
    "excludeSoftwareItemsByDisclosureLevel",
    "disclosureLevelWhitelist",
    "taxonomyKeyValueSeperator",
    "taxonomyRepeatingValueSeparator"
})
@XmlRootElement(name = "stylesheet")
public class Stylesheet {

    @XmlElement(required = true)
    protected String subscriptionName;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String output;
    @XmlElement(name = "imported-styles", required = true)
    protected ImportedStyles importedStyles;
    @XmlElement(name = "proj_path_seperator", required = true)
    protected String projPathSeperator;
    @XmlElement(name = "proj_path_parts", required = true)
    protected String projPathParts;
    @XmlElement(name = "proj_namespace_types", required = true)
    protected ProjNamespaceTypes projNamespaceTypes;
    @XmlElement(name = "proj_is_smartfolder", required = true)
    protected String projIsSmartfolder;
    @XmlElement(name = "embedded_criteria_filter", required = true)
    protected String embeddedCriteriaFilter;
    @XmlElement(required = true)
    protected String filter;
    @XmlElement(required = true)
    protected String delivery;
    @XmlElement(required = true)
    protected String smartfolder;
    @XmlElement(required = true)
    protected HierarchyExpansions hierarchyExpansions;
    @XmlElement(name = "stylesheet_name", required = true)
    protected String stylesheetName;
    @XmlElement(name = "FastRepeatingValueSeparator", required = true)
    protected String fastRepeatingValueSeparator;
    @XmlElement(required = true)
    protected String currentProjNamespace;
    @XmlElement(name = "exclude_software-items_by_disclosure-level", required = true)
    protected String excludeSoftwareItemsByDisclosureLevel;
    @XmlElement(name = "disclosure-level_whitelist", required = true)
    protected DisclosureLevelWhitelist disclosureLevelWhitelist;
    @XmlElement(name = "TaxonomyKeyValueSeperator", required = true)
    protected String taxonomyKeyValueSeperator;
    @XmlElement(name = "TaxonomyRepeatingValueSeparator", required = true)
    protected String taxonomyRepeatingValueSeparator;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String base;

    /**
     * Gets the value of the subscriptionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionName() {
        return subscriptionName;
    }

    /**
     * Sets the value of the subscriptionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionName(String value) {
        this.subscriptionName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutput(String value) {
        this.output = value;
    }

    /**
     * Gets the value of the importedStyles property.
     * 
     * @return
     *     possible object is
     *     {@link ImportedStyles }
     *     
     */
    public ImportedStyles getImportedStyles() {
        return importedStyles;
    }

    /**
     * Sets the value of the importedStyles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportedStyles }
     *     
     */
    public void setImportedStyles(ImportedStyles value) {
        this.importedStyles = value;
    }

    /**
     * Gets the value of the projPathSeperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjPathSeperator() {
        return projPathSeperator;
    }

    /**
     * Sets the value of the projPathSeperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjPathSeperator(String value) {
        this.projPathSeperator = value;
    }

    /**
     * Gets the value of the projPathParts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjPathParts() {
        return projPathParts;
    }

    /**
     * Sets the value of the projPathParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjPathParts(String value) {
        this.projPathParts = value;
    }

    /**
     * Gets the value of the projNamespaceTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ProjNamespaceTypes }
     *     
     */
    public ProjNamespaceTypes getProjNamespaceTypes() {
        return projNamespaceTypes;
    }

    /**
     * Sets the value of the projNamespaceTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjNamespaceTypes }
     *     
     */
    public void setProjNamespaceTypes(ProjNamespaceTypes value) {
        this.projNamespaceTypes = value;
    }

    /**
     * Gets the value of the projIsSmartfolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjIsSmartfolder() {
        return projIsSmartfolder;
    }

    /**
     * Sets the value of the projIsSmartfolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjIsSmartfolder(String value) {
        this.projIsSmartfolder = value;
    }

    /**
     * Gets the value of the embeddedCriteriaFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbeddedCriteriaFilter() {
        return embeddedCriteriaFilter;
    }

    /**
     * Sets the value of the embeddedCriteriaFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbeddedCriteriaFilter(String value) {
        this.embeddedCriteriaFilter = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelivery(String value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the smartfolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmartfolder() {
        return smartfolder;
    }

    /**
     * Sets the value of the smartfolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmartfolder(String value) {
        this.smartfolder = value;
    }

    /**
     * Gets the value of the hierarchyExpansions property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyExpansions }
     *     
     */
    public HierarchyExpansions getHierarchyExpansions() {
        return hierarchyExpansions;
    }

    /**
     * Sets the value of the hierarchyExpansions property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyExpansions }
     *     
     */
    public void setHierarchyExpansions(HierarchyExpansions value) {
        this.hierarchyExpansions = value;
    }

    /**
     * Gets the value of the stylesheetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStylesheetName() {
        return stylesheetName;
    }

    /**
     * Sets the value of the stylesheetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStylesheetName(String value) {
        this.stylesheetName = value;
    }

    /**
     * Gets the value of the fastRepeatingValueSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastRepeatingValueSeparator() {
        return fastRepeatingValueSeparator;
    }

    /**
     * Sets the value of the fastRepeatingValueSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastRepeatingValueSeparator(String value) {
        this.fastRepeatingValueSeparator = value;
    }

    /**
     * Gets the value of the currentProjNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentProjNamespace() {
        return currentProjNamespace;
    }

    /**
     * Sets the value of the currentProjNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentProjNamespace(String value) {
        this.currentProjNamespace = value;
    }

    /**
     * Gets the value of the excludeSoftwareItemsByDisclosureLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludeSoftwareItemsByDisclosureLevel() {
        return excludeSoftwareItemsByDisclosureLevel;
    }

    /**
     * Sets the value of the excludeSoftwareItemsByDisclosureLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludeSoftwareItemsByDisclosureLevel(String value) {
        this.excludeSoftwareItemsByDisclosureLevel = value;
    }

    /**
     * Gets the value of the disclosureLevelWhitelist property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosureLevelWhitelist }
     *     
     */
    public DisclosureLevelWhitelist getDisclosureLevelWhitelist() {
        return disclosureLevelWhitelist;
    }

    /**
     * Sets the value of the disclosureLevelWhitelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosureLevelWhitelist }
     *     
     */
    public void setDisclosureLevelWhitelist(DisclosureLevelWhitelist value) {
        this.disclosureLevelWhitelist = value;
    }

    /**
     * Gets the value of the taxonomyKeyValueSeperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxonomyKeyValueSeperator() {
        return taxonomyKeyValueSeperator;
    }

    /**
     * Sets the value of the taxonomyKeyValueSeperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxonomyKeyValueSeperator(String value) {
        this.taxonomyKeyValueSeperator = value;
    }

    /**
     * Gets the value of the taxonomyRepeatingValueSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxonomyRepeatingValueSeparator() {
        return taxonomyRepeatingValueSeparator;
    }

    /**
     * Sets the value of the taxonomyRepeatingValueSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxonomyRepeatingValueSeparator(String value) {
        this.taxonomyRepeatingValueSeparator = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
