//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:06 AM IST 
//


package com.hp.concentra.bindings.output.schema.marketingstandard;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pubv_vendor"/>
 *         &lt;element ref="{}pubv_inventory_policy"/>
 *         &lt;element ref="{}pubv_order_limit"/>
 *         &lt;element ref="{}pubv_restriction"/>
 *         &lt;element ref="{}pubv_strict_hold_flag"/>
 *         &lt;element ref="{}pubv_unit_code"/>
 *         &lt;element ref="{}pubv_initial_quantity"/>
 *         &lt;element ref="{}pubv_initial_air_quantity"/>
 *         &lt;element ref="{}pubv_reorder_quantity"/>
 *         &lt;element ref="{}pubv_initial_date"/>
 *         &lt;element ref="{}gsb_application_type"/>
 *         &lt;element ref="{}gsb_content_type"/>
 *         &lt;element ref="{}gsb_business_type"/>
 *         &lt;element ref="{}stock_unit_price"/>
 *         &lt;element ref="{}stock_unit_weight"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pubvVendor",
    "pubvInventoryPolicy",
    "pubvOrderLimit",
    "pubvRestriction",
    "pubvStrictHoldFlag",
    "pubvUnitCode",
    "pubvInitialQuantity",
    "pubvInitialAirQuantity",
    "pubvReorderQuantity",
    "pubvInitialDate",
    "gsbApplicationType",
    "gsbContentType",
    "gsbBusinessType",
    "stockUnitPrice",
    "stockUnitWeight"
})
@XmlRootElement(name = "pub_vendor_detail")
public class PubVendorDetail {

    @XmlElement(name = "pubv_vendor", required = true)
    protected String pubvVendor;
    @XmlElement(name = "pubv_inventory_policy", required = true)
    protected String pubvInventoryPolicy;
    @XmlElement(name = "pubv_order_limit", required = true)
    protected BigInteger pubvOrderLimit;
    @XmlElement(name = "pubv_restriction", required = true)
    protected PubvRestriction pubvRestriction;
    @XmlElement(name = "pubv_strict_hold_flag", required = true)
    protected BigInteger pubvStrictHoldFlag;
    @XmlElement(name = "pubv_unit_code", required = true)
    protected String pubvUnitCode;
    @XmlElement(name = "pubv_initial_quantity", required = true)
    protected BigInteger pubvInitialQuantity;
    @XmlElement(name = "pubv_initial_air_quantity", required = true)
    protected BigInteger pubvInitialAirQuantity;
    @XmlElement(name = "pubv_reorder_quantity", required = true)
    protected BigInteger pubvReorderQuantity;
    @XmlElement(name = "pubv_initial_date", required = true, nillable = true)
    protected XMLGregorianCalendar pubvInitialDate;
    @XmlElement(name = "gsb_application_type", required = true)
    protected String gsbApplicationType;
    @XmlElement(name = "gsb_content_type", required = true)
    protected String gsbContentType;
    @XmlElement(name = "gsb_business_type", required = true)
    protected String gsbBusinessType;
    @XmlElement(name = "stock_unit_price", required = true)
    protected String stockUnitPrice;
    @XmlElement(name = "stock_unit_weight", required = true)
    protected String stockUnitWeight;

    /**
     * Gets the value of the pubvVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubvVendor() {
        return pubvVendor;
    }

    /**
     * Sets the value of the pubvVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubvVendor(String value) {
        this.pubvVendor = value;
    }

    /**
     * Gets the value of the pubvInventoryPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubvInventoryPolicy() {
        return pubvInventoryPolicy;
    }

    /**
     * Sets the value of the pubvInventoryPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubvInventoryPolicy(String value) {
        this.pubvInventoryPolicy = value;
    }

    /**
     * Gets the value of the pubvOrderLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPubvOrderLimit() {
        return pubvOrderLimit;
    }

    /**
     * Sets the value of the pubvOrderLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPubvOrderLimit(BigInteger value) {
        this.pubvOrderLimit = value;
    }

    /**
     * Gets the value of the pubvRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link PubvRestriction }
     *     
     */
    public PubvRestriction getPubvRestriction() {
        return pubvRestriction;
    }

    /**
     * Sets the value of the pubvRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PubvRestriction }
     *     
     */
    public void setPubvRestriction(PubvRestriction value) {
        this.pubvRestriction = value;
    }

    /**
     * Gets the value of the pubvStrictHoldFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPubvStrictHoldFlag() {
        return pubvStrictHoldFlag;
    }

    /**
     * Sets the value of the pubvStrictHoldFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPubvStrictHoldFlag(BigInteger value) {
        this.pubvStrictHoldFlag = value;
    }

    /**
     * Gets the value of the pubvUnitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubvUnitCode() {
        return pubvUnitCode;
    }

    /**
     * Sets the value of the pubvUnitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubvUnitCode(String value) {
        this.pubvUnitCode = value;
    }

    /**
     * Gets the value of the pubvInitialQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPubvInitialQuantity() {
        return pubvInitialQuantity;
    }

    /**
     * Sets the value of the pubvInitialQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPubvInitialQuantity(BigInteger value) {
        this.pubvInitialQuantity = value;
    }

    /**
     * Gets the value of the pubvInitialAirQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPubvInitialAirQuantity() {
        return pubvInitialAirQuantity;
    }

    /**
     * Sets the value of the pubvInitialAirQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPubvInitialAirQuantity(BigInteger value) {
        this.pubvInitialAirQuantity = value;
    }

    /**
     * Gets the value of the pubvReorderQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPubvReorderQuantity() {
        return pubvReorderQuantity;
    }

    /**
     * Sets the value of the pubvReorderQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPubvReorderQuantity(BigInteger value) {
        this.pubvReorderQuantity = value;
    }

    /**
     * Gets the value of the pubvInitialDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPubvInitialDate() {
        return pubvInitialDate;
    }

    /**
     * Sets the value of the pubvInitialDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPubvInitialDate(XMLGregorianCalendar value) {
        this.pubvInitialDate = value;
    }

    /**
     * Gets the value of the gsbApplicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGsbApplicationType() {
        return gsbApplicationType;
    }

    /**
     * Sets the value of the gsbApplicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGsbApplicationType(String value) {
        this.gsbApplicationType = value;
    }

    /**
     * Gets the value of the gsbContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGsbContentType() {
        return gsbContentType;
    }

    /**
     * Sets the value of the gsbContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGsbContentType(String value) {
        this.gsbContentType = value;
    }

    /**
     * Gets the value of the gsbBusinessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGsbBusinessType() {
        return gsbBusinessType;
    }

    /**
     * Sets the value of the gsbBusinessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGsbBusinessType(String value) {
        this.gsbBusinessType = value;
    }

    /**
     * Gets the value of the stockUnitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockUnitPrice() {
        return stockUnitPrice;
    }

    /**
     * Sets the value of the stockUnitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockUnitPrice(String value) {
        this.stockUnitPrice = value;
    }

    /**
     * Gets the value of the stockUnitWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockUnitWeight() {
        return stockUnitWeight;
    }

    /**
     * Sets the value of the stockUnitWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockUnitWeight(String value) {
        this.stockUnitWeight = value;
    }

}
