//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 11:03:03 AM IST 
//


package com.hp.concentra.bindings.input.schema.marketinghho;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}company_info"/>
 *         &lt;element ref="{}r_object_id"/>
 *         &lt;element ref="{}priority"/>
 *         &lt;element ref="{}products"/>
 *         &lt;element ref="{}document_type"/>
 *         &lt;element ref="{}version_label"/>
 *         &lt;element ref="{}property_update_date"/>
 *         &lt;element ref="{}content_update_date"/>
 *         &lt;element ref="{}language_codes"/>
 *         &lt;element ref="{}products"/>
 *         &lt;element ref="{}r_object_type"/>
 *         &lt;element ref="{}full_title"/>
 *         &lt;element ref="{}language_label"/>
 *         &lt;element ref="{}content_type"/>
 *         &lt;element ref="{}authors"/>
 *         &lt;element ref="{}regions"/>
 *         &lt;element ref="{}document_type_details"/>
 *         &lt;element ref="{}activity_type_details"/>
 *         &lt;element ref="{}go_to_market_initiatives"/>
 *         &lt;element ref="{}subject_types"/>
 *         &lt;element ref="{}contacts"/>
 *         &lt;element ref="{}associated_project_pages"/>
 *         &lt;element ref="{}search_keywords"/>
 *         &lt;element ref="{}master_object_name"/>
 *         &lt;element ref="{}audiences"/>
 *         &lt;element ref="{}file_name"/>
 *         &lt;element ref="{}components"/>
 *         &lt;element ref="{}has_valid_products"/>
 *         &lt;element ref="{}activity_difficulty_level"/>
 *         &lt;element ref="{}activity_duration"/>
 *         &lt;element ref="{}activity_type"/>
 *         &lt;element ref="{}go_to_market_window"/>
 *         &lt;element ref="{}holiday"/>
 *         &lt;element ref="{}season"/>
 *         &lt;element ref="{}col_id"/>
 *         &lt;element ref="{}campaign_association"/>
 *         &lt;element ref="{}content_version_date"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}disclosure_level"/>
 *         &lt;element ref="{}content_version"/>
 *         &lt;element ref="{}featured_activity_flag"/>
 *         &lt;element ref="{}language_code"/>
 *         &lt;element ref="{}licensing_rights"/>
 *         &lt;element ref="{}media_size"/>
 *         &lt;element ref="{}object_name"/>
 *         &lt;element ref="{}original_system"/>
 *         &lt;element ref="{}project_id"/>
 *         &lt;element ref="{}document_class"/>
 *         &lt;element ref="{}review_date"/>
 *         &lt;element ref="{}file_bytes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "document")
public class Document {

    @XmlElementRefs({
        @XmlElementRef(name = "master_object_name", type = JAXBElement.class),
        @XmlElementRef(name = "version_label", type = JAXBElement.class),
        @XmlElementRef(name = "document_type", type = JAXBElement.class),
        @XmlElementRef(name = "company_info", type = JAXBElement.class),
        @XmlElementRef(name = "go_to_market_window", type = JAXBElement.class),
        @XmlElementRef(name = "featured_activity_flag", type = JAXBElement.class),
        @XmlElementRef(name = "disclosure_level", type = JAXBElement.class),
        @XmlElementRef(name = "document_class", type = JAXBElement.class),
        @XmlElementRef(name = "file_bytes", type = JAXBElement.class),
        @XmlElementRef(name = "regions", type = Regions.class),
        @XmlElementRef(name = "season", type = JAXBElement.class),
        @XmlElementRef(name = "media_size", type = JAXBElement.class),
        @XmlElementRef(name = "original_system", type = JAXBElement.class),
        @XmlElementRef(name = "document_type_details", type = DocumentTypeDetails.class),
        @XmlElementRef(name = "campaign_association", type = JAXBElement.class),
        @XmlElementRef(name = "review_date", type = JAXBElement.class),
        @XmlElementRef(name = "priority", type = JAXBElement.class),
        @XmlElementRef(name = "description", type = JAXBElement.class),
        @XmlElementRef(name = "content_version", type = JAXBElement.class),
        @XmlElementRef(name = "products", type = Products.class),
        @XmlElementRef(name = "r_object_id", type = JAXBElement.class),
        @XmlElementRef(name = "subject_types", type = SubjectTypes.class),
        @XmlElementRef(name = "activity_difficulty_level", type = JAXBElement.class),
        @XmlElementRef(name = "associated_project_pages", type = AssociatedProjectPages.class),
        @XmlElementRef(name = "activity_duration", type = JAXBElement.class),
        @XmlElementRef(name = "components", type = Components.class),
        @XmlElementRef(name = "object_name", type = JAXBElement.class),
        @XmlElementRef(name = "file_name", type = JAXBElement.class),
        @XmlElementRef(name = "project_id", type = JAXBElement.class),
        @XmlElementRef(name = "authors", type = Authors.class),
        @XmlElementRef(name = "content_version_date", type = JAXBElement.class),
        @XmlElementRef(name = "go_to_market_initiatives", type = GoToMarketInitiatives.class),
        @XmlElementRef(name = "holiday", type = JAXBElement.class),
        @XmlElementRef(name = "activity_type_details", type = ActivityTypeDetails.class),
        @XmlElementRef(name = "audiences", type = Audiences.class),
        @XmlElementRef(name = "search_keywords", type = SearchKeywords.class),
        @XmlElementRef(name = "r_object_type", type = JAXBElement.class),
        @XmlElementRef(name = "activity_type", type = JAXBElement.class),
        @XmlElementRef(name = "col_id", type = JAXBElement.class),
        @XmlElementRef(name = "language_code", type = LanguageCode.class),
        @XmlElementRef(name = "full_title", type = FullTitle.class),
        @XmlElementRef(name = "property_update_date", type = JAXBElement.class),
        @XmlElementRef(name = "content_type", type = JAXBElement.class),
        @XmlElementRef(name = "has_valid_products", type = JAXBElement.class),
        @XmlElementRef(name = "licensing_rights", type = JAXBElement.class),
        @XmlElementRef(name = "language_codes", type = LanguageCodes.class),
        @XmlElementRef(name = "contacts", type = Contacts.class),
        @XmlElementRef(name = "content_update_date", type = JAXBElement.class),
        @XmlElementRef(name = "language_label", type = JAXBElement.class)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Products" is used by two different parts of a schema. See: 
     * line 111 of file:/C:/Users/RADHA/PROJECTS/CDSPLUS/cdsp-bindings/schema/input/concentra/marketinghho.xsd
     * line 105 of file:/C:/Users/RADHA/PROJECTS/CDSPLUS/cdsp-bindings/schema/input/concentra/marketinghho.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link Regions }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link DocumentTypeDetails }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link Byte }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link Products }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link SubjectTypes }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link AssociatedProjectPages }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Components }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Authors }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link GoToMarketInitiatives }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link ActivityTypeDetails }
     * {@link Audiences }
     * {@link SearchKeywords }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link LanguageCode }
     * {@link FullTitle }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link LanguageCodes }
     * {@link Contacts }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
